-- migration_018: Add Florida and New York programs to the catalog.
--
-- Nine programs per state covering: Medicaid, SNAP, TANF, state housing
-- finance, LIHEAP, workforce/unemployment, veterans, aging, and the
-- statewide 211 row. All rows use the migration_017 schema (max_monthly_income
-- with HH=2 baseline, min_age, max_age, required_situations).
--
-- Florida Medicaid is gated by required_situations rather than a wider
-- income cap because Florida did not expand Medicaid: most childless,
-- non-pregnant, non-disabled adults do not qualify regardless of income.
-- Better to under-match accurately than over-match misleadingly.
--
-- NY HEAP cap is calibrated to 60% State Median Income (NY's actual
-- HEAP eligibility threshold), not 150% FPL — NY's HEAP is more generous
-- than most states', and using FPL would produce false negatives.

insert into programs (
  name, category, description, potential_benefit, who_qualifies,
  phone_number, apply_url, benefit_value, scope, state, jurisdiction_name,
  slug, is_active, important_notes, eligibility_rules
) values

-- ============================================================
-- FLORIDA (9)
-- ============================================================
(
  'Florida Medicaid',
  'Health Insurance',
  'Florida Medicaid (Statewide Medicaid Managed Care) provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Florida did not expand Medicaid for non-disabled adults, so most adult coverage is limited to parents of minor children, pregnant women, and people with disabilities.',
  'Full health coverage at little to no cost',
  'Low-income parents of minor children, pregnant women, people with disabilities, seniors, and children',
  '1-866-762-2237',
  'https://www.myflfamilies.com/services/public-assistance/access',
  15000,
  'state',
  'FL',
  null,
  'florida-medicaid',
  true,
  'Florida did not expand Medicaid. Most adults without children, disability, or pregnancy do not qualify regardless of income.',
  '{"max_monthly_income": 2350, "min_age": null, "max_age": null, "required_situations": ["single_parent", "pregnant", "disability"]}'::jsonb
),
(
  'Florida SNAP (Food Assistance Program)',
  'Food Assistance',
  'Florida''s Food Assistance Program (SNAP) provides monthly food benefits on an EBT card that works at most grocery stores and farmers markets. Apply through the DCF ACCESS Florida portal.',
  'Up to ~$975/month for a family of four',
  'Florida households with gross monthly income at or below 200% of the federal poverty level (broad-based categorical eligibility)',
  '1-866-762-2237',
  'https://www.myflfamilies.com/services/public-assistance/access',
  11676,
  'state',
  'FL',
  null,
  'florida-snap',
  true,
  null,
  '{"max_monthly_income": 3400, "min_age": null, "max_age": null, "required_situations": []}'::jsonb
),
(
  'Florida Temporary Cash Assistance (TCA)',
  'Cash Assistance',
  'Florida''s Temporary Cash Assistance program provides monthly cash benefits for very low-income families with minor children, plus job placement and child-care help.',
  'Up to ~$303/month for a family of three',
  'Florida families with minor children and very low income',
  '1-866-762-2237',
  'https://www.myflfamilies.com/services/public-assistance/access',
  3500,
  'state',
  'FL',
  null,
  'florida-tca',
  true,
  null,
  '{"max_monthly_income": 1000, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb
),
(
  'Florida Hometown Heroes Housing Program',
  'Housing Assistance',
  'Florida Housing Finance Corporation''s Hometown Heroes program provides down-payment and closing-cost assistance up to $35,000 for first-time homebuyers in eligible occupations (educators, healthcare workers, first responders, military, and others) earning at or below 150% of area median income.',
  'Up to $35,000 in down-payment and closing-cost assistance',
  'First-time homebuyers in eligible Florida occupations earning at or below 150% AMI',
  '1-850-488-4197',
  'https://www.floridahousing.org/programs/homebuyer-overview-page',
  10000,
  'state',
  'FL',
  null,
  'florida-hometown-heroes',
  true,
  null,
  '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb
),
(
  'Florida LIHEAP',
  'Utility Assistance',
  'Florida''s federally-funded Low-Income Home Energy Assistance Program helps qualifying households pay heating, cooling, and crisis energy bills. Administered by FloridaCommerce through local community-action agencies.',
  '$300–$1,500 per year toward energy bills',
  'Florida households with income at or below 150% of the federal poverty level',
  '1-850-717-8450',
  'https://www.commerce.fl.gov/community-development/community-services/low-income-home-energy-assistance-program-liheap',
  1300,
  'state',
  'FL',
  null,
  'florida-liheap',
  true,
  'LIHEAP funds are distributed through local Community Action Agencies — call 211 to find your local provider.',
  '{"max_monthly_income": 2550, "min_age": null, "max_age": null, "required_situations": []}'::jsonb
),
(
  'Florida Reemployment Assistance',
  'Income Assistance',
  'Weekly cash benefits for Floridians who lost their job through no fault of their own. Apply online with FloridaCommerce. Benefits run up to 12 weeks; you must be actively searching for work.',
  'Up to $275/week ($14,300/year max)',
  'Workers laid off through no fault of their own with sufficient base-period earnings',
  '1-833-352-7759',
  'https://floridajobs.org/Reemployment-Assistance-Service-Center',
  13000,
  'state',
  'FL',
  null,
  'florida-reemployment-assistance',
  true,
  null,
  '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb
),
(
  'Florida Department of Veterans'' Affairs',
  'Veteran Services',
  'The state agency that helps Florida veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through county Veteran Service Officers.',
  'Free benefits counseling plus access to state veterans homes and emergency funds',
  'Florida veterans, active-duty service members, and their dependents',
  '1-844-693-5838',
  'https://www.fdva.state.fl.us',
  5000,
  'state',
  'FL',
  null,
  'florida-veterans-affairs',
  true,
  null,
  '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb
),
(
  'Florida Elder Helpline',
  'Senior Services',
  'Statewide Florida helpline operated by the Department of Elder Affairs that connects callers to local Aging & Disability Resource Centers (ADRCs) for meals, transportation, in-home care, benefits counseling, and caregiver support.',
  '~$2,000/year in services (meals, transport, care coordination)',
  'Floridians 60 and older and their family caregivers',
  '1-800-963-5337',
  'https://elderaffairs.org',
  2000,
  'state',
  'FL',
  null,
  'florida-elder-helpline',
  true,
  null,
  '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb
),
(
  'Florida 211',
  'Information & Referral',
  'Florida 211 is the statewide health and human services helpline. Call 2-1-1 or visit fl211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
  'Free referral to local assistance programs',
  'Anyone in Florida needing help finding local services',
  '211',
  'https://fl211.org',
  0,
  'state',
  'FL',
  null,
  'florida-211',
  true,
  null,
  '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb
),

-- ============================================================
-- NEW YORK (9)
-- ============================================================
(
  'New York Medicaid',
  'Health Insurance',
  'New York Medicaid provides full health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. New York expanded Medicaid for adults under the ACA. Apply through NY State of Health.',
  'Full health coverage at little to no cost',
  'New York adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
  '1-800-541-2831',
  'https://nystateofhealth.ny.gov',
  15000,
  'state',
  'NY',
  null,
  'new-york-medicaid',
  true,
  null,
  '{"max_monthly_income": 2350, "min_age": null, "max_age": null, "required_situations": []}'::jsonb
),
(
  'New York SNAP',
  'Food Assistance',
  'New York''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Apply through MyBenefits or your local social services district.',
  'Up to ~$975/month for a family of four',
  'New York households with gross monthly income at or below 130% of the federal poverty level',
  '1-800-342-3009',
  'https://otda.ny.gov/programs/snap',
  11676,
  'state',
  'NY',
  null,
  'new-york-snap',
  true,
  null,
  '{"max_monthly_income": 2200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb
),
(
  'New York Family Assistance (TANF)',
  'Cash Assistance',
  'Monthly cash assistance for low-income New York families with minor children, plus access to employment and training services. Administered by OTDA through local social services districts.',
  'Up to ~$789/month for a family of three (varies by district)',
  'New York families with minor children and limited income/resources',
  '1-800-342-3009',
  'https://otda.ny.gov/programs/temporary-assistance',
  3500,
  'state',
  'NY',
  null,
  'new-york-family-assistance',
  true,
  null,
  '{"max_monthly_income": 1500, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb
),
(
  'State of New York Mortgage Agency (SONYMA)',
  'Housing Assistance',
  'SONYMA offers low-interest fixed-rate mortgages and down-payment assistance to first-time homebuyers, with income and home-price limits that vary by county.',
  'Down-payment assistance plus below-market mortgage rates',
  'First-time homebuyers in New York meeting county-specific income and home-price limits',
  '1-800-382-4663',
  'https://hcr.ny.gov/sonyma',
  10000,
  'state',
  'NY',
  null,
  'new-york-sonyma',
  true,
  null,
  '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb
),
(
  'New York HEAP (Home Energy Assistance Program)',
  'Utility Assistance',
  'New York''s Home Energy Assistance Program helps qualifying households pay heating bills and emergency energy crises. Eligibility is based on 60% of State Median Income, which is more generous than most states'' LIHEAP programs.',
  '$200–$1,500 per year toward heating bills',
  'New York households with income at or below 60% of State Median Income (~$5,100/mo for a household of two)',
  '1-800-342-3009',
  'https://otda.ny.gov/programs/heap',
  1300,
  'state',
  'NY',
  null,
  'new-york-heap',
  true,
  null,
  '{"max_monthly_income": 5100, "min_age": null, "max_age": null, "required_situations": []}'::jsonb
),
(
  'New York Unemployment Insurance',
  'Income Assistance',
  'Weekly cash benefits for New Yorkers who lost their job through no fault of their own. Administered by the NY State Department of Labor. Most claimants receive benefits for up to 26 weeks; you must be actively searching for work.',
  'Up to $504/week ($26,200/year max)',
  'Workers laid off through no fault of their own with sufficient base-period earnings',
  '1-888-209-8124',
  'https://dol.ny.gov/unemployment-page',
  13000,
  'state',
  'NY',
  null,
  'new-york-unemployment',
  true,
  null,
  '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb
),
(
  'New York State Department of Veterans'' Services',
  'Veteran Services',
  'The state agency that helps New York veterans access VA benefits, education aid (including the New York Veterans Tuition Awards), employment, healthcare, and emergency assistance.',
  'Free benefits counseling plus access to state veterans cemeteries, homes, and emergency funds',
  'New York veterans, active-duty service members, and their dependents',
  '1-888-838-7697',
  'https://veterans.ny.gov',
  5000,
  'state',
  'NY',
  null,
  'new-york-veterans-services',
  true,
  null,
  '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb
),
(
  'New York State Office for the Aging',
  'Senior Services',
  'NYSOFA''s NY Connects helpline is the statewide entry point to a network of 59 Area Agencies on Aging that provide seniors with help locating services — meals, transportation, in-home care, caregiver support, benefits counseling, and elder abuse prevention.',
  '~$2,000/year in services (meals, transport, care coordination)',
  'New Yorkers 60 and older and their family caregivers',
  '1-844-697-6321',
  'https://aging.ny.gov',
  2000,
  'state',
  'NY',
  null,
  'new-york-aging',
  true,
  null,
  '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb
),
(
  'New York 211',
  'Information & Referral',
  'New York 211 is the statewide health and human services helpline. Call 2-1-1 or visit 211newyork.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
  'Free referral to local assistance programs',
  'Anyone in New York needing help finding local services',
  '211',
  'https://www.211newyork.org',
  0,
  'state',
  'NY',
  null,
  'new-york-211',
  true,
  null,
  '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb
);
