-- migration_034: Add Rhode Island, South Dakota, Utah, Vermont.
--
-- 32 rows — 8 categories per state. Housing finance slot omitted.
--
-- All four are expansion states. Rhode Island and Vermont were day-one
-- ACA expansion (2014). Utah expanded after Proposition 3 (2018) — full
-- expansion took effect January 2020. South Dakota is a recent expansion:
-- voters passed Constitutional Amendment D in November 2022 and adult
-- coverage took effect July 2023 — the SD row carries an important_notes
-- flag for annual re-verification (parallel to NC and MO).
--
-- LIHEAPs at 60% SMI (modeled as 200% FPL with the standard SMI note):
-- Rhode Island Energy Assistance, South Dakota LIHEAP, Vermont Fuel
-- Assistance. Utah HEAT at 150% FPL (federal default — no SMI note).
--
-- SNAP BBCE: RI 185% FPL, VT 185% FPL. SD and UT at 130% federal default
-- (neither state has Broad-Based Categorical Eligibility).

insert into programs (
  name, category, description, potential_benefit, who_qualifies,
  phone_number, apply_url, benefit_value, scope, state, jurisdiction_name,
  slug, is_active, important_notes, eligibility_rules
) values

-- ── RHODE ISLAND ────────────────────────────────────────────────────
('Rhode Island Medicaid', 'Health Insurance',
 'Rhode Island Medicaid (including RIte Care for families and RIte Share for adults) provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Rhode Island expanded Medicaid for adults under the ACA in 2014. Apply through HealthSource RI.',
 'Full health coverage at little to no cost',
 'Rhode Island adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-855-840-4774', 'https://healthsourceri.com',
 15000, 'state', 'RI', null, 'rhode-island-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Rhode Island SNAP', 'Food Assistance',
 'Rhode Island''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by the Department of Human Services.',
 'Up to ~$975/month for a family of four',
 'Rhode Island households with gross monthly income at or below 185% of the federal poverty level (state-expanded threshold via BBCE)',
 '1-855-697-4347', 'https://dhs.ri.gov/programs-services/supplemental-nutrition-assistance-program-snap',
 11676, 'state', 'RI', null, 'rhode-island-snap', true, null,
 '{"max_income_percent_fpl": 185, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Rhode Island Works (RIWorks)', 'Cash Assistance',
 'Monthly cash assistance for low-income Rhode Island families with minor children, plus access to employment and training services. Administered by the Department of Human Services.',
 'Up to ~$721/month for a family of three',
 'Rhode Island families with minor children and limited income/resources',
 '1-855-697-4347', 'https://dhs.ri.gov/programs-services/rhode-island-works-program-riworks',
 3500, 'state', 'RI', null, 'rhode-island-riworks', true, null,
 '{"max_monthly_income": 1300, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Rhode Island Energy Assistance Program (LIHEAP)', 'Utility Assistance',
 'Rhode Island''s federally-funded Low Income Home Energy Assistance Program helps qualifying households pay heating bills, weatherization, and crisis energy needs. Administered by the Office of Energy Resources through Community Action Agencies.',
 '$300–$1,500 per year toward heating bills',
 'Rhode Island households with income at or below 60% of State Median Income (~200% FPL)',
 '401-462-5300', 'https://energy.ri.gov/programs-incentives/income-based-energy-assistance/liheap',
 1300, 'state', 'RI', null, 'rhode-island-liheap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Rhode Island Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Rhode Islanders who lost their job through no fault of their own. Administered by the Department of Labor and Training. Most claimants receive benefits for up to 26 weeks.',
 'Up to $705/week plus dependent allowance (~$36,700/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '401-415-6772', 'https://dlt.ri.gov/individuals/unemployment-insurance',
 13000, 'state', 'RI', null, 'rhode-island-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Rhode Island Office of Veterans Services', 'Veteran Services',
 'The state agency that helps Rhode Island veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and the Rhode Island Veterans Home in Bristol.',
 'Free benefits counseling plus access to state veterans home',
 'Rhode Island veterans, active-duty service members, and their dependents',
 '401-462-0324', 'https://veterans.ri.gov',
 5000, 'state', 'RI', null, 'rhode-island-veterans-services', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Rhode Island Office of Healthy Aging (OHA)', 'Senior Services',
 'The Office of Healthy Aging coordinates Rhode Island''s 1 statewide Area Agency on Aging through THE POINT, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Rhode Islanders 60 and older and their family caregivers',
 '401-462-4444', 'https://oha.ri.gov',
 2000, 'state', 'RI', null, 'rhode-island-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Rhode Island 211 (United Way)', 'Information & Referral',
 'United Way of Rhode Island 211 is the statewide health and human services helpline. Call 2-1-1 or visit 211ri.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Rhode Island needing help finding local services',
 '211', 'https://www.211ri.org',
 0, 'state', 'RI', null, 'rhode-island-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── SOUTH DAKOTA (expansion as of July 2023) ────────────────────────
('South Dakota Medicaid', 'Health Insurance',
 'South Dakota Medicaid provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. South Dakota voters approved Medicaid expansion via Constitutional Amendment D in November 2022, with adult coverage taking effect July 2023.',
 'Full health coverage at little to no cost',
 'South Dakota adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-877-999-5612', 'https://dss.sd.gov/medicaid',
 15000, 'state', 'SD', null, 'south-dakota-medicaid', true,
 'South Dakota voters passed Medicaid expansion via Constitutional Amendment D in 2022; adult coverage took effect July 2023. Annual verification should re-confirm status.',
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('South Dakota SNAP', 'Food Assistance',
 'South Dakota''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by the Department of Social Services.',
 'Up to ~$975/month for a family of four',
 'South Dakota households with gross monthly income at or below 130% of the federal poverty level',
 '1-877-999-5612', 'https://dss.sd.gov/foodstamps',
 11676, 'state', 'SD', null, 'south-dakota-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('South Dakota TANF', 'Cash Assistance',
 'Monthly cash assistance for low-income South Dakota families with minor children, plus access to employment and training services. Administered by the Department of Social Services.',
 'Up to ~$615/month for a family of three',
 'South Dakota families with minor children and limited income/resources',
 '1-877-999-5612', 'https://dss.sd.gov/economicassistance/tanf',
 3500, 'state', 'SD', null, 'south-dakota-tanf', true, null,
 '{"max_monthly_income": 1100, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('South Dakota LIHEAP', 'Utility Assistance',
 'South Dakota''s federally-funded LIHEAP helps qualifying households pay heating bills and crisis energy needs. Administered by the Department of Social Services.',
 '$300–$1,500 per year toward heating bills',
 'South Dakota households with income at or below 60% of State Median Income (~200% FPL)',
 '1-800-233-8503', 'https://dss.sd.gov/economicassistance/energyassistance',
 1300, 'state', 'SD', null, 'south-dakota-liheap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('South Dakota Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for South Dakotans who lost their job through no fault of their own. Administered by the South Dakota Department of Labor and Regulation. Most claimants receive benefits for up to 26 weeks.',
 'Up to $549/week (~$28,500/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '605-626-3179', 'https://dlr.sd.gov/ra',
 13000, 'state', 'SD', null, 'south-dakota-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('South Dakota Department of Veterans Affairs', 'Veteran Services',
 'The state agency that helps South Dakota veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through County Veterans Service Officers and the Michael J. Fitzmaurice State Veterans Home in Hot Springs.',
 'Free benefits counseling plus access to state veterans home',
 'South Dakota veterans, active-duty service members, and their dependents',
 '605-773-7251', 'https://vetaffairs.sd.gov',
 5000, 'state', 'SD', null, 'south-dakota-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('South Dakota Adult Services and Aging', 'Senior Services',
 'The Department of Human Services Division of Adult Services and Aging coordinates South Dakota''s 4 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'South Dakotans 60 and older and their family caregivers',
 '1-866-854-5465', 'https://dhs.sd.gov/asa',
 2000, 'state', 'SD', null, 'south-dakota-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('South Dakota 211 (Helpline Center)', 'Information & Referral',
 'South Dakota 211 is the statewide health and human services helpline operated by the Helpline Center. Call 2-1-1 or visit helplinecenter.org/2-1-1 to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in South Dakota needing help finding local services',
 '211', 'https://www.helplinecenter.org/2-1-1-community-resources',
 0, 'state', 'SD', null, 'south-dakota-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── UTAH ────────────────────────────────────────────────────────────
('Utah Medicaid', 'Health Insurance',
 'Utah Medicaid provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Utah expanded Medicaid for adults after voters approved Proposition 3 in 2018; full expansion took effect January 2020. Apply through Utah Department of Workforce Services.',
 'Full health coverage at little to no cost',
 'Utah adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-866-435-7414', 'https://medicaid.utah.gov',
 15000, 'state', 'UT', null, 'utah-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Utah SNAP (Food Stamps)', 'Food Assistance',
 'Utah''s Supplemental Nutrition Assistance Program provides monthly food benefits on a Horizon EBT card. Administered by the Department of Workforce Services through myCase.',
 'Up to ~$975/month for a family of four',
 'Utah households with gross monthly income at or below 130% of the federal poverty level',
 '1-866-435-7414', 'https://jobs.utah.gov/customereducation/services/foodassistance',
 11676, 'state', 'UT', null, 'utah-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Utah Family Employment Program (FEP)', 'Cash Assistance',
 'Monthly cash assistance for low-income Utah families with minor children, plus access to employment and training services. Administered by the Department of Workforce Services.',
 'Up to ~$498/month for a family of three',
 'Utah families with minor children and limited income/resources',
 '1-866-435-7414', 'https://jobs.utah.gov/customereducation/services/financial',
 3500, 'state', 'UT', null, 'utah-fep', true, null,
 '{"max_monthly_income": 900, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Utah HEAT (Home Energy Assistance Target)', 'Utility Assistance',
 'Utah''s federally-funded HEAT program helps qualifying households pay heating bills, cooling bills, and crisis energy needs. Administered by the Department of Workforce Services Office of Energy Development through Community Action Partnerships.',
 '$300–$1,500 per year toward heating bills',
 'Utah households with income at or below 150% of the federal poverty level',
 '1-866-435-7414', 'https://jobs.utah.gov/housing/scso/seal/heat.html',
 1300, 'state', 'UT', null, 'utah-heat', true, null,
 '{"max_income_percent_fpl": 150, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Utah Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Utahns who lost their job through no fault of their own. Administered by the Utah Department of Workforce Services. Most claimants receive benefits for up to 26 weeks.',
 'Up to $727/week (~$37,800/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '801-526-4400', 'https://jobs.utah.gov/ui/home',
 13000, 'state', 'UT', null, 'utah-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Utah Department of Veterans and Military Affairs', 'Veteran Services',
 'The state agency that helps Utah veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and four Utah State Veterans Homes.',
 'Free benefits counseling plus access to state veterans homes',
 'Utah veterans, active-duty service members, and their dependents',
 '801-326-2372', 'https://veterans.utah.gov',
 5000, 'state', 'UT', null, 'utah-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Utah Aging and Adult Services', 'Senior Services',
 'The Department of Human Services Division of Aging and Adult Services coordinates Utah''s 12 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Utahns 60 and older and their family caregivers',
 '801-538-3910', 'https://daas.utah.gov',
 2000, 'state', 'UT', null, 'utah-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Utah 211 (United Way)', 'Information & Referral',
 'Utah 211 is the statewide health and human services helpline operated by United Way of Salt Lake. Call 2-1-1 or visit 211utah.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Utah needing help finding local services',
 '211', 'https://211utah.org',
 0, 'state', 'UT', null, 'utah-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── VERMONT ─────────────────────────────────────────────────────────
('Vermont Medicaid (Green Mountain Care)', 'Health Insurance',
 'Vermont Medicaid (including Dr. Dynasaur for children) provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Vermont expanded Medicaid for adults under the ACA in 2014. Apply through Vermont Health Connect.',
 'Full health coverage at little to no cost',
 'Vermont adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-855-899-9600', 'https://portal.healthconnect.vermont.gov',
 15000, 'state', 'VT', null, 'vermont-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Vermont 3SquaresVT (SNAP)', 'Food Assistance',
 'Vermont''s Supplemental Nutrition Assistance Program (3SquaresVT) provides monthly food benefits on a Vermont EBT card. Administered by the Department for Children and Families Economic Services Division.',
 'Up to ~$975/month for a family of four',
 'Vermont households with gross monthly income at or below 185% of the federal poverty level (state-expanded threshold via BBCE)',
 '1-800-479-6151', 'https://dcf.vermont.gov/benefits/3SquaresVT',
 11676, 'state', 'VT', null, 'vermont-snap', true, null,
 '{"max_income_percent_fpl": 185, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Vermont Reach Up (TANF)', 'Cash Assistance',
 'Monthly cash assistance for low-income Vermont families with minor children, plus access to employment and training services. Administered by the Department for Children and Families Economic Services Division.',
 'Up to ~$863/month for a family of three',
 'Vermont families with minor children and limited income/resources',
 '1-800-479-6151', 'https://dcf.vermont.gov/benefits/Reach-Up',
 3500, 'state', 'VT', null, 'vermont-reach-up', true, null,
 '{"max_monthly_income": 1500, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Vermont Fuel Assistance (Seasonal LIHEAP)', 'Utility Assistance',
 'Vermont''s federally-funded Seasonal Fuel Assistance program (LIHEAP) helps qualifying households pay heating bills and crisis energy needs. Administered by the Department for Children and Families Economic Services Division.',
 '$300–$1,500 per year toward heating bills',
 'Vermont households with income at or below 60% of State Median Income (~200% FPL)',
 '1-800-479-6151', 'https://dcf.vermont.gov/benefits/fuel-assistance',
 1300, 'state', 'VT', null, 'vermont-fuel-assistance', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Vermont Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Vermonters who lost their job through no fault of their own. Administered by the Vermont Department of Labor. Most claimants receive benefits for up to 26 weeks.',
 'Up to $705/week (~$36,700/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-877-214-3330', 'https://labor.vermont.gov/unemployment-insurance',
 13000, 'state', 'VT', null, 'vermont-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Vermont Office of Veterans Affairs', 'Veteran Services',
 'The state agency that helps Vermont veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and the Vermont Veterans'' Home in Bennington.',
 'Free benefits counseling plus access to state veterans home',
 'Vermont veterans, active-duty service members, and their dependents',
 '802-828-3379', 'https://veterans.vermont.gov',
 5000, 'state', 'VT', null, 'vermont-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Vermont Department of Disabilities, Aging and Independent Living (DAIL)', 'Senior Services',
 'DAIL coordinates Vermont''s 5 Area Agencies on Aging through the Senior Helpline, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Vermonters 60 and older and their family caregivers',
 '1-800-642-5119', 'https://dail.vermont.gov',
 2000, 'state', 'VT', null, 'vermont-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Vermont 211', 'Information & Referral',
 'Vermont 211 is the statewide health and human services helpline operated by United Ways of Vermont. Call 2-1-1 or visit vermont211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Vermont needing help finding local services',
 '211', 'https://vermont211.org',
 0, 'state', 'VT', null, 'vermont-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb);
