-- migration_032: Add Maine, Maryland, North Dakota, Oregon, South Carolina.
--
-- 40 rows — 8 categories per state (Medicaid, SNAP, TANF, LIHEAP,
-- unemployment, veterans, aging, 211). The state housing finance slot is
-- deliberately omitted (see migration_028 / catalog inclusion principles
-- in TODO.md).
--
-- South Carolina is non-expansion — south-carolina-medicaid is gated by
-- ["single_parent","pregnant","disability"] like FL/AL/GA/MS/KS/TN/WY.
-- Maine (MaineCare 2019), Maryland (HealthChoice), North Dakota (Medicaid
-- Expansion 2014), and Oregon (Oregon Health Plan) are all expansion
-- states with no required_situations gate.
--
-- LIHEAPs at 60% SMI (modeled as 200% FPL with the standard SMI note):
-- Maine HEAP, ND LIHEAP, Oregon Energy Assistance Program. Maryland OHEP
-- at 175% FPL (state-expanded but FPL-based) — no SMI note. SC LIEAP at
-- federal default 150% — no SMI note.
--
-- SNAP BBCE thresholds (Broad-Based Categorical Eligibility lifts the
-- 130% federal floor for these states):
--   ME: 185% FPL
--   MD: 200% FPL
--   ND: 200% FPL
--   OR: 200% FPL
--   SC: 130% FPL (no BBCE — federal default)
--
-- Note: federal SNAP and federal LIHEAP rows were deactivated in
-- migration_030 and so are NOT a fallback for these new states; the
-- state rows below are the only SNAP/LIHEAP coverage these states get.

insert into programs (
  name, category, description, potential_benefit, who_qualifies,
  phone_number, apply_url, benefit_value, scope, state, jurisdiction_name,
  slug, is_active, important_notes, eligibility_rules
) values

-- ── MAINE ───────────────────────────────────────────────────────────
('MaineCare (Maine Medicaid)', 'Health Insurance',
 'MaineCare is the state Medicaid program, providing health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Maine expanded Medicaid for adults in 2019 under the ACA.',
 'Full health coverage at little to no cost',
 'Maine adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-855-797-4357', 'https://www.maine.gov/dhhs/ofi/programs-services/mainecare',
 15000, 'state', 'ME', null, 'maine-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Maine SNAP (Food Supplement Program)', 'Food Assistance',
 'Maine''s Supplemental Nutrition Assistance Program (Food Supplement Program) provides monthly food benefits on a Pine Tree Card. Administered by the Department of Health and Human Services Office for Family Independence.',
 'Up to ~$975/month for a family of four',
 'Maine households with gross monthly income at or below 185% of the federal poverty level (state-expanded threshold via BBCE)',
 '1-855-797-4357', 'https://www.maine.gov/dhhs/ofi/programs-services/food-supplement',
 11676, 'state', 'ME', null, 'maine-snap', true, null,
 '{"max_income_percent_fpl": 185, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Maine TANF', 'Cash Assistance',
 'Monthly cash assistance for low-income Maine families with minor children, plus access to ASPIRE employment and training services. Administered by the Office for Family Independence.',
 'Up to ~$610/month for a family of three',
 'Maine families with minor children and limited income/resources',
 '1-855-797-4357', 'https://www.maine.gov/dhhs/ofi/programs-services/tanf',
 3500, 'state', 'ME', null, 'maine-tanf', true, null,
 '{"max_monthly_income": 1000, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Maine HEAP (Home Energy Assistance Program)', 'Utility Assistance',
 'Maine''s federally-funded Home Energy Assistance Program helps qualifying households pay heating bills and crisis energy needs. Administered by MaineHousing through Community Action Agencies.',
 '$300–$1,500 per year toward heating bills',
 'Maine households with income at or below 60% of State Median Income (~200% FPL)',
 '1-800-452-4668', 'https://www.mainehousing.org/programs-services/energy/energydetails/home-energy-assistance-program-(heap)',
 1300, 'state', 'ME', null, 'maine-heap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Maine Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Mainers who lost their job through no fault of their own. Administered by the Maine Department of Labor. Most claimants receive benefits for up to 26 weeks.',
 'Up to $538/week (~$28,000/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-800-593-7660', 'https://www.maine.gov/labor/unemployment',
 13000, 'state', 'ME', null, 'maine-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Maine Bureau of Veterans'' Services', 'Veteran Services',
 'The state agency that helps Maine veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and the Maine Veterans'' Homes.',
 'Free benefits counseling plus access to state veterans homes',
 'Maine veterans, active-duty service members, and their dependents',
 '1-207-430-6035', 'https://www.maine.gov/veterans',
 5000, 'state', 'ME', null, 'maine-veterans-services', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Maine Office of Aging and Disability Services (OADS)', 'Senior Services',
 'OADS coordinates Maine''s 5 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Mainers 60 and older and their family caregivers',
 '1-800-262-2232', 'https://www.maine.gov/dhhs/oads',
 2000, 'state', 'ME', null, 'maine-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Maine 211', 'Information & Referral',
 'Maine 211 is the statewide health and human services helpline operated by United Ways of Maine. Call 2-1-1 or visit 211maine.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Maine needing help finding local services',
 '211', 'https://211maine.org',
 0, 'state', 'ME', null, 'maine-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── MARYLAND ────────────────────────────────────────────────────────
('Maryland Medicaid (HealthChoice)', 'Health Insurance',
 'Maryland Medicaid (HealthChoice) provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Maryland expanded Medicaid for adults under the ACA. Apply through Maryland Health Connection.',
 'Full health coverage at little to no cost',
 'Maryland adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-855-642-8572', 'https://www.marylandhealthconnection.gov',
 15000, 'state', 'MD', null, 'maryland-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Maryland Food Supplement Program (SNAP)', 'Food Assistance',
 'Maryland''s Supplemental Nutrition Assistance Program (Food Supplement Program) provides monthly food benefits on an Independence Card. Administered by the Department of Human Services.',
 'Up to ~$975/month for a family of four',
 'Maryland households with gross monthly income at or below 200% of the federal poverty level (state-expanded threshold via BBCE)',
 '1-800-332-6347', 'https://dhs.maryland.gov/food-supplement-program',
 11676, 'state', 'MD', null, 'maryland-snap', true, null,
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Maryland Temporary Cash Assistance (TCA)', 'Cash Assistance',
 'Monthly cash assistance for low-income Maryland families with minor children, plus access to employment and training services. Administered by the Department of Human Services.',
 'Up to ~$813/month for a family of three',
 'Maryland families with minor children and limited income/resources',
 '1-800-332-6347', 'https://dhs.maryland.gov/temporary-cash-assistance',
 3500, 'state', 'MD', null, 'maryland-tca', true, null,
 '{"max_monthly_income": 1300, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Maryland Energy Assistance Program (MEAP/OHEP)', 'Utility Assistance',
 'Maryland''s federally-funded Office of Home Energy Programs (OHEP) administers the Maryland Energy Assistance Program (MEAP) and Electric Universal Service Program (EUSP). Helps qualifying households pay heating, cooling, and crisis energy bills.',
 '$300–$1,500 per year toward energy bills',
 'Maryland households with income at or below 175% of the federal poverty level (state-expanded threshold)',
 '1-800-332-6347', 'https://dhs.maryland.gov/office-of-home-energy-programs',
 1300, 'state', 'MD', null, 'maryland-meap', true, null,
 '{"max_income_percent_fpl": 175, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Maryland Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Marylanders who lost their job through no fault of their own. Administered by the Maryland Department of Labor. Most claimants receive benefits for up to 26 weeks.',
 'Up to $430/week (~$22,400/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-667-207-6520', 'https://labor.maryland.gov/employment/unemployment.shtml',
 13000, 'state', 'MD', null, 'maryland-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Maryland Department of Veterans & Military Families', 'Veteran Services',
 'The state agency that helps Maryland veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Service Program Officers and the Charlotte Hall Veterans Home.',
 'Free benefits counseling plus access to state veterans home',
 'Maryland veterans, active-duty service members, and their dependents',
 '410-260-3838', 'https://veterans.maryland.gov',
 5000, 'state', 'MD', null, 'maryland-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Maryland Department of Aging', 'Senior Services',
 'Maryland''s Department of Aging coordinates the state''s 19 Area Agencies on Aging through the Maryland Access Point (MAP) network, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Marylanders 60 and older and their family caregivers',
 '1-844-627-5465', 'https://aging.maryland.gov',
 2000, 'state', 'MD', null, 'maryland-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Maryland 211', 'Information & Referral',
 'Maryland 211 is the statewide health and human services helpline operated by 211 Maryland. Call 2-1-1 or visit 211md.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Maryland needing help finding local services',
 '211', 'https://211md.org',
 0, 'state', 'MD', null, 'maryland-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── NORTH DAKOTA ────────────────────────────────────────────────────
('North Dakota Medicaid Expansion', 'Health Insurance',
 'North Dakota Medicaid provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. North Dakota expanded Medicaid for adults under the ACA in 2014.',
 'Full health coverage at little to no cost',
 'North Dakota adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-844-854-4825', 'https://www.hhs.nd.gov/healthcare/medicaid',
 15000, 'state', 'ND', null, 'north-dakota-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('North Dakota SNAP', 'Food Assistance',
 'North Dakota''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by the Department of Health and Human Services.',
 'Up to ~$975/month for a family of four',
 'North Dakota households with gross monthly income at or below 200% of the federal poverty level (state-expanded threshold via BBCE)',
 '1-800-755-2716', 'https://www.hhs.nd.gov/snap',
 11676, 'state', 'ND', null, 'north-dakota-snap', true, null,
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('North Dakota TANF', 'Cash Assistance',
 'Monthly cash assistance for low-income North Dakota families with minor children, plus access to employment and training services. Administered by the Department of Health and Human Services.',
 'Up to ~$486/month for a family of three',
 'North Dakota families with minor children and limited income/resources',
 '1-800-755-2716', 'https://www.hhs.nd.gov/tanf',
 3500, 'state', 'ND', null, 'north-dakota-tanf', true, null,
 '{"max_monthly_income": 900, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('North Dakota LIHEAP', 'Utility Assistance',
 'North Dakota''s federally-funded LIHEAP helps qualifying households pay heating bills and crisis energy needs. Administered by the Department of Health and Human Services.',
 '$300–$1,500 per year toward heating bills',
 'North Dakota households with income at or below 60% of State Median Income (~200% FPL)',
 '1-800-755-2716', 'https://www.hhs.nd.gov/liheap',
 1300, 'state', 'ND', null, 'north-dakota-liheap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('North Dakota Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for North Dakotans who lost their job through no fault of their own. Administered by Job Service North Dakota. Most claimants receive benefits for up to 26 weeks.',
 'Up to $748/week (~$38,900/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '701-328-4995', 'https://www.jobsnd.com/unemployment-individuals',
 13000, 'state', 'ND', null, 'north-dakota-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('North Dakota Department of Veterans Affairs', 'Veteran Services',
 'The state agency that helps North Dakota veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through County Veterans Service Officers and the North Dakota Veterans Home in Lisbon.',
 'Free benefits counseling plus access to state veterans home',
 'North Dakota veterans, active-duty service members, and their dependents',
 '701-239-7165', 'https://www.veterans.nd.gov',
 5000, 'state', 'ND', null, 'north-dakota-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('North Dakota Aging Services Division', 'Senior Services',
 'The Aging Services Division within ND HHS coordinates the state''s 8 Area Agencies on Aging through the Aging and Disability Resource-LINK, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'North Dakotans 60 and older and their family caregivers',
 '1-855-462-5465', 'https://www.hhs.nd.gov/agingservices',
 2000, 'state', 'ND', null, 'north-dakota-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('North Dakota 211', 'Information & Referral',
 'North Dakota 211 is the statewide health and human services helpline operated by FirstLink. Call 2-1-1 or visit nd211.com to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in North Dakota needing help finding local services',
 '211', 'https://nd211.com',
 0, 'state', 'ND', null, 'north-dakota-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── OREGON ──────────────────────────────────────────────────────────
('Oregon Health Plan (Oregon Medicaid)', 'Health Insurance',
 'The Oregon Health Plan is the state Medicaid program, providing health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Oregon expanded Medicaid for adults under the ACA in 2014.',
 'Full health coverage at little to no cost',
 'Oregon adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-800-699-9075', 'https://www.oregon.gov/oha/hsd/ohp',
 15000, 'state', 'OR', null, 'oregon-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Oregon SNAP', 'Food Assistance',
 'Oregon''s Supplemental Nutrition Assistance Program provides monthly food benefits on an Oregon Trail EBT card. Administered by the Oregon Department of Human Services.',
 'Up to ~$975/month for a family of four',
 'Oregon households with gross monthly income at or below 200% of the federal poverty level (state-expanded threshold via BBCE)',
 '1-855-503-7233', 'https://www.oregon.gov/odhs/food/Pages/snap.aspx',
 11676, 'state', 'OR', null, 'oregon-snap', true, null,
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Oregon TANF', 'Cash Assistance',
 'Monthly cash assistance for low-income Oregon families with minor children, plus access to JOBS employment and training services. Administered by the Oregon Department of Human Services.',
 'Up to ~$506/month for a family of three',
 'Oregon families with minor children and limited income/resources',
 '1-855-503-7233', 'https://www.oregon.gov/odhs/cash/Pages/tanf.aspx',
 3500, 'state', 'OR', null, 'oregon-tanf', true, null,
 '{"max_monthly_income": 1000, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Oregon Energy Assistance (LIHEAP/OEAP)', 'Utility Assistance',
 'Oregon''s federally-funded LIHEAP and state-funded Oregon Energy Assistance Program (OEAP) help qualifying households pay heating, cooling, and crisis energy bills. Administered by the Oregon Housing and Community Services through Community Action Agencies.',
 '$300–$1,500 per year toward energy bills',
 'Oregon households with income at or below 60% of State Median Income (~200% FPL)',
 '1-800-453-5511', 'https://www.oregon.gov/ohcs/energy-weatherization',
 1300, 'state', 'OR', null, 'oregon-liheap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Oregon Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Oregonians who lost their job through no fault of their own. Administered by the Oregon Employment Department. Most claimants receive benefits for up to 26 weeks.',
 'Up to $836/week (~$43,500/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-877-345-3484', 'https://unemployment.oregon.gov',
 13000, 'state', 'OR', null, 'oregon-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Oregon Department of Veterans'' Affairs', 'Veteran Services',
 'The state agency that helps Oregon veterans access VA benefits, education aid, employment, healthcare, home loans, and emergency assistance through County Veterans Service Officers and the Oregon Veterans'' Homes.',
 'Free benefits counseling plus access to state veterans homes',
 'Oregon veterans, active-duty service members, and their dependents',
 '1-800-692-9666', 'https://www.oregon.gov/odva',
 5000, 'state', 'OR', null, 'oregon-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Oregon Aging and People with Disabilities (APD)', 'Senior Services',
 'Oregon DHS''s Aging and People with Disabilities program coordinates the state''s 17 Area Agencies on Aging through the ADRC of Oregon, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Oregonians 60 and older and their family caregivers',
 '1-855-673-2372', 'https://www.oregon.gov/odhs/aging-disability/Pages/default.aspx',
 2000, 'state', 'OR', null, 'oregon-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Oregon 211 (211info)', 'Information & Referral',
 'Oregon 211 (211info) is the statewide health and human services helpline. Call 2-1-1 or visit 211info.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Oregon needing help finding local services',
 '211', 'https://211info.org',
 0, 'state', 'OR', null, 'oregon-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── SOUTH CAROLINA (non-expansion) ──────────────────────────────────
('South Carolina Healthy Connections (Medicaid)', 'Health Insurance',
 'Healthy Connections is South Carolina''s Medicaid program, providing health coverage including doctor visits, hospital care, prescriptions, and preventive services. South Carolina did not expand Medicaid; adult eligibility is limited to parents of minor children, pregnant women, and people with disabilities.',
 'Full health coverage at little to no cost',
 'Low-income parents of minor children, pregnant women, people with disabilities, seniors, and children',
 '1-888-549-0820', 'https://www.scdhhs.gov',
 15000, 'state', 'SC', null, 'south-carolina-medicaid', true,
 'South Carolina did not expand Medicaid. Most adults without children, disability, or pregnancy do not qualify regardless of income.',
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": ["single_parent", "pregnant", "disability"]}'::jsonb),
('South Carolina SNAP', 'Food Assistance',
 'South Carolina''s Supplemental Nutrition Assistance Program provides monthly food benefits on an SC Health & Human Services EBT card. Administered by the Department of Social Services.',
 'Up to ~$975/month for a family of four',
 'South Carolina households with gross monthly income at or below 130% of the federal poverty level',
 '1-800-616-1309', 'https://dss.sc.gov/snap',
 11676, 'state', 'SC', null, 'south-carolina-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('South Carolina Family Independence (TANF)', 'Cash Assistance',
 'Monthly cash assistance for low-income South Carolina families with minor children, plus access to employment and training services. Administered by the Department of Social Services.',
 'Up to ~$292/month for a family of three',
 'South Carolina families with minor children and very low income',
 '1-800-616-1309', 'https://dss.sc.gov/family-independence',
 3500, 'state', 'SC', null, 'south-carolina-family-independence', true, null,
 '{"max_monthly_income": 750, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('South Carolina Energy Assistance (LIEAP)', 'Utility Assistance',
 'South Carolina''s federally-funded Low Income Energy Assistance Program helps qualifying households pay heating, cooling, and crisis energy bills. Administered by the Office of Economic Opportunity through Community Action Agencies.',
 '$300–$1,500 per year toward energy bills',
 'South Carolina households with income at or below 150% of the federal poverty level',
 '1-803-734-2145', 'https://oeo.sc.gov/programs/energy-assistance',
 1300, 'state', 'SC', null, 'south-carolina-lieap', true, null,
 '{"max_income_percent_fpl": 150, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('South Carolina Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for South Carolinians who lost their job through no fault of their own. Administered by the Department of Employment and Workforce. Most claimants receive benefits for up to 20 weeks.',
 'Up to $326/week (~$17,000/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-866-831-1724', 'https://dew.sc.gov',
 13000, 'state', 'SC', null, 'south-carolina-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('South Carolina Department of Veterans'' Affairs', 'Veteran Services',
 'The state agency that helps South Carolina veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through County Veterans Affairs Officers and the SC Veterans Nursing Homes.',
 'Free benefits counseling plus access to state veterans homes',
 'South Carolina veterans, active-duty service members, and their dependents',
 '803-647-2434', 'https://scdva.sc.gov',
 5000, 'state', 'SC', null, 'south-carolina-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('South Carolina Department on Aging', 'Senior Services',
 'The Department on Aging coordinates South Carolina''s 10 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'South Carolinians 60 and older and their family caregivers',
 '1-800-868-9095', 'https://aging.sc.gov',
 2000, 'state', 'SC', null, 'south-carolina-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('South Carolina 211', 'Information & Referral',
 'South Carolina 211 is the statewide health and human services helpline operated by United Way Association of South Carolina. Call 2-1-1 or visit sc211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in South Carolina needing help finding local services',
 '211', 'https://sc211.org',
 0, 'state', 'SC', null, 'south-carolina-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb);
