-- migration_035: Add Virginia, Wisconsin, West Virginia, District of Columbia.
--
-- 32 rows — 8 categories per state. Housing finance slot omitted.
--
-- This is the final batch — after this migration the catalog covers all
-- 50 states + DC.
--
-- Wisconsin is a UNIQUE Medicaid case. Wisconsin neither expanded to 138%
-- FPL (ACA expansion) nor stayed at pre-ACA limits (traditional non-
-- expansion). It uses BadgerCare Plus to cover all adults up to 100% FPL
-- via a Medicaid 1115 waiver. Childless adults <100% FPL qualify (unlike
-- most non-expansion states), but adults 100-138% FPL fall into a gap and
-- must use the marketplace. Modeled here as max_income_percent_fpl=100
-- with no required_situations, plus an important_notes flag explaining
-- the BadgerCare nuance.
--
-- Virginia (FAMIS Plus / Cover Virginia): expansion took effect January
-- 2019 — stable enough that no important_notes flag is needed.
-- DC: expansion 2014. WV: expansion 2014. All standard.
--
-- LIHEAPs at 60% SMI (modeled as 200% FPL with the standard SMI note):
-- DC LIHEAP, WV LIHEAP, Wisconsin Home Energy Plus. Virginia EAP at
-- 150% FPL (federal default — no SMI note).
--
-- SNAP BBCE: All four use 200% FPL via Broad-Based Categorical
-- Eligibility (DC, WI long-standing; VA and WV adopted post-2020).

insert into programs (
  name, category, description, potential_benefit, who_qualifies,
  phone_number, apply_url, benefit_value, scope, state, jurisdiction_name,
  slug, is_active, important_notes, eligibility_rules
) values

-- ── VIRGINIA ────────────────────────────────────────────────────────
('Virginia Medicaid (Cover Virginia)', 'Health Insurance',
 'Virginia Medicaid (FAMIS Plus for adults, FAMIS for children) provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Virginia expanded Medicaid for adults under the ACA in January 2019. Apply through Cover Virginia.',
 'Full health coverage at little to no cost',
 'Virginia adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-855-242-8282', 'https://coverva.dmas.virginia.gov',
 15000, 'state', 'VA', null, 'virginia-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Virginia SNAP', 'Food Assistance',
 'Virginia''s Supplemental Nutrition Assistance Program provides monthly food benefits on a Virginia EBT card. Administered by the Department of Social Services through CommonHelp.',
 'Up to ~$975/month for a family of four',
 'Virginia households with gross monthly income at or below 200% of the federal poverty level (state-expanded threshold via BBCE)',
 '1-855-635-4370', 'https://commonhelp.virginia.gov',
 11676, 'state', 'VA', null, 'virginia-snap', true, null,
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Virginia Initiative for Education and Work (VIEW/TANF)', 'Cash Assistance',
 'Monthly cash assistance for low-income Virginia families with minor children, plus access to VIEW employment and training services. Administered by the Department of Social Services.',
 'Up to ~$432/month for a family of three',
 'Virginia families with minor children and limited income/resources',
 '1-855-635-4370', 'https://www.dss.virginia.gov/benefit/tanf.cgi',
 3500, 'state', 'VA', null, 'virginia-tanf', true, null,
 '{"max_monthly_income": 900, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Virginia Energy Assistance Program (LIHEAP)', 'Utility Assistance',
 'Virginia''s federally-funded Energy Assistance Program helps qualifying households pay heating, cooling, and crisis energy bills. Administered by the Department of Social Services through local DSS offices.',
 '$300–$1,500 per year toward energy bills',
 'Virginia households with income at or below 150% of the federal poverty level',
 '1-855-635-4370', 'https://www.dss.virginia.gov/benefit/ea.cgi',
 1300, 'state', 'VA', null, 'virginia-liheap', true, null,
 '{"max_income_percent_fpl": 150, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Virginia Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Virginians who lost their job through no fault of their own. Administered by the Virginia Employment Commission. Most claimants receive benefits for up to 26 weeks.',
 'Up to $378/week (~$19,700/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-866-832-2363', 'https://www.vec.virginia.gov',
 13000, 'state', 'VA', null, 'virginia-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Virginia Department of Veterans Services', 'Veteran Services',
 'The state agency that helps Virginia veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and four Virginia Veterans Care Centers.',
 'Free benefits counseling plus access to state veterans care centers',
 'Virginia veterans, active-duty service members, and their dependents',
 '804-786-0719', 'https://www.dvs.virginia.gov',
 5000, 'state', 'VA', null, 'virginia-veterans-services', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Virginia Department for Aging and Rehabilitative Services (DARS)', 'Senior Services',
 'DARS coordinates Virginia''s 25 Area Agencies on Aging through the No Wrong Door network, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Virginians 60 and older and their family caregivers',
 '1-800-552-3402', 'https://www.dars.virginia.gov',
 2000, 'state', 'VA', null, 'virginia-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Virginia 211', 'Information & Referral',
 'Virginia 211 is the statewide health and human services helpline operated by Council of Community Services. Call 2-1-1 or visit 211virginia.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Virginia needing help finding local services',
 '211', 'https://211virginia.org',
 0, 'state', 'VA', null, 'virginia-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── WISCONSIN (BadgerCare — neither traditional expansion nor non-expansion) ──
('BadgerCare Plus (Wisconsin Medicaid)', 'Health Insurance',
 'BadgerCare Plus is Wisconsin''s combined Medicaid and CHIP program, providing health coverage for adults up to 100% of the federal poverty level via a Medicaid 1115 waiver. Children, pregnant women, and certain other groups qualify at higher limits. Wisconsin did not adopt full ACA Medicaid expansion to 138% FPL.',
 'Full health coverage at little to no cost',
 'Wisconsin adults at or below 100% of the federal poverty level, children up to 300% FPL, pregnant women up to 306% FPL',
 '1-800-362-3002', 'https://access.wisconsin.gov',
 15000, 'state', 'WI', null, 'wisconsin-medicaid', true,
 'Wisconsin uses BadgerCare Plus to cover adults up to 100% FPL via a Medicaid 1115 waiver, rather than the ACA expansion to 138% FPL. Adults at 100-138% FPL fall into a coverage gap and must purchase coverage on the marketplace with subsidies. Children, pregnant women, and disability populations qualify at higher thresholds.',
 '{"max_income_percent_fpl": 100, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Wisconsin FoodShare (SNAP)', 'Food Assistance',
 'FoodShare is Wisconsin''s Supplemental Nutrition Assistance Program, providing monthly food benefits on a Wisconsin QUEST card. Administered by the Department of Health Services.',
 'Up to ~$975/month for a family of four',
 'Wisconsin households with gross monthly income at or below 200% of the federal poverty level (state-expanded threshold via BBCE)',
 '1-800-362-3002', 'https://www.dhs.wisconsin.gov/foodshare',
 11676, 'state', 'WI', null, 'wisconsin-snap', true, null,
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Wisconsin Works (W-2)', 'Cash Assistance',
 'Monthly cash assistance for low-income Wisconsin families with minor children, paired with employment placements at one of four W-2 tiers. Administered by the Department of Children and Families through W-2 agencies.',
 'Up to ~$673/month for a family of three',
 'Wisconsin families with minor children and limited income/resources',
 '1-866-826-9276', 'https://dcf.wisconsin.gov/wisconsinworks',
 3500, 'state', 'WI', null, 'wisconsin-w2', true, null,
 '{"max_monthly_income": 1100, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Wisconsin Home Energy Plus (LIHEAP)', 'Utility Assistance',
 'Wisconsin''s federally-funded Home Energy Plus program (Wisconsin Heating Energy Assistance Program) helps qualifying households pay heating bills, weatherization, and crisis energy needs. Administered by the Department of Administration through county and tribal agencies.',
 '$300–$1,500 per year toward heating bills',
 'Wisconsin households with income at or below 60% of State Median Income (~200% FPL)',
 '1-866-432-8947', 'https://homeenergyplus.wi.gov',
 1300, 'state', 'WI', null, 'wisconsin-liheap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Wisconsin Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Wisconsinites who lost their job through no fault of their own. Administered by the Wisconsin Department of Workforce Development. Most claimants receive benefits for up to 26 weeks.',
 'Up to $370/week (~$19,200/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-844-910-3661', 'https://dwd.wisconsin.gov/uiben',
 13000, 'state', 'WI', null, 'wisconsin-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Wisconsin Department of Veterans Affairs', 'Veteran Services',
 'The state agency that helps Wisconsin veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through County Veterans Service Officers and three Wisconsin Veterans Homes.',
 'Free benefits counseling plus access to state veterans homes',
 'Wisconsin veterans, active-duty service members, and their dependents',
 '1-800-947-8387', 'https://dva.wi.gov',
 5000, 'state', 'WI', null, 'wisconsin-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Wisconsin Bureau of Aging and Disability Resources (BADR)', 'Senior Services',
 'BADR coordinates Wisconsin''s 13 Area Agencies on Aging and 71 Aging and Disability Resource Centers (ADRCs), connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Wisconsinites 60 and older and their family caregivers',
 '608-266-2536', 'https://www.dhs.wisconsin.gov/aging',
 2000, 'state', 'WI', null, 'wisconsin-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Wisconsin 211', 'Information & Referral',
 'Wisconsin 211 is the statewide health and human services helpline operated by United Way of Wisconsin through 7 regional 211 centers. Call 2-1-1 or visit 211wisconsin.communityos.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Wisconsin needing help finding local services',
 '211', 'https://211wisconsin.communityos.org',
 0, 'state', 'WI', null, 'wisconsin-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── WEST VIRGINIA ───────────────────────────────────────────────────
('West Virginia Medicaid', 'Health Insurance',
 'West Virginia Medicaid provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. West Virginia expanded Medicaid for adults under the ACA in 2014. Apply through inROADS.',
 'Full health coverage at little to no cost',
 'West Virginia adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-877-716-1212', 'https://dhhr.wv.gov/bms',
 15000, 'state', 'WV', null, 'west-virginia-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('West Virginia SNAP', 'Food Assistance',
 'West Virginia''s Supplemental Nutrition Assistance Program provides monthly food benefits on a Mountain State EBT card. Administered by the Department of Human Services.',
 'Up to ~$975/month for a family of four',
 'West Virginia households with gross monthly income at or below 200% of the federal poverty level (state-expanded threshold via BBCE)',
 '1-877-716-1212', 'https://dhs.wv.gov/bcf/services/Pages/SNAP.aspx',
 11676, 'state', 'WV', null, 'west-virginia-snap', true, null,
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('West Virginia WORKS (TANF)', 'Cash Assistance',
 'Monthly cash assistance for low-income West Virginia families with minor children, plus access to employment and training services. Administered by the Department of Human Services.',
 'Up to ~$542/month for a family of three',
 'West Virginia families with minor children and limited income/resources',
 '1-877-716-1212', 'https://dhs.wv.gov/bcf/services/Pages/WV-WORKS-TANF.aspx',
 3500, 'state', 'WV', null, 'west-virginia-works', true, null,
 '{"max_monthly_income": 1000, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('West Virginia LIHEAP', 'Utility Assistance',
 'West Virginia''s federally-funded LIHEAP helps qualifying households pay heating bills and crisis energy needs. Administered by the Department of Human Services through local DHS offices.',
 '$300–$1,500 per year toward heating bills',
 'West Virginia households with income at or below 60% of State Median Income (~200% FPL)',
 '1-877-716-1212', 'https://dhs.wv.gov/bcf/services/Pages/Utility-Assistance.aspx',
 1300, 'state', 'WV', null, 'west-virginia-liheap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('West Virginia Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for West Virginians who lost their job through no fault of their own. Administered by WorkForce West Virginia. Most claimants receive benefits for up to 26 weeks.',
 'Up to $662/week (~$34,400/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-800-379-1032', 'https://workforcewv.org',
 13000, 'state', 'WV', null, 'west-virginia-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('West Virginia Department of Veterans Assistance', 'Veteran Services',
 'The state agency that helps West Virginia veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and the West Virginia Veterans Home in Barboursville.',
 'Free benefits counseling plus access to state veterans home',
 'West Virginia veterans, active-duty service members, and their dependents',
 '304-558-3661', 'https://veterans.wv.gov',
 5000, 'state', 'WV', null, 'west-virginia-veterans-services', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('West Virginia Bureau of Senior Services', 'Senior Services',
 'The Bureau of Senior Services coordinates West Virginia''s 4 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'West Virginians 60 and older and their family caregivers',
 '1-877-987-3646', 'https://bosseniorservices.wv.gov',
 2000, 'state', 'WV', null, 'west-virginia-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('West Virginia 211', 'Information & Referral',
 'West Virginia 211 is the statewide health and human services helpline. Call 2-1-1 or visit wv211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in West Virginia needing help finding local services',
 '211', 'https://wv211.org',
 0, 'state', 'WV', null, 'west-virginia-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── DISTRICT OF COLUMBIA ────────────────────────────────────────────
('DC Medicaid (DC Healthy Families / Healthcare Alliance)', 'Health Insurance',
 'DC Medicaid provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. DC expanded Medicaid for adults under the ACA in 2014, with one of the most generous adult-coverage thresholds in the country (up to 215% FPL for parents and childless adults, modeled here at the standard 138% baseline).',
 'Full health coverage at little to no cost',
 'DC adults at or below 138% of the federal poverty level (and up to 215% for parents and childless adults under DC''s expanded thresholds), plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '202-727-5355', 'https://dhcf.dc.gov',
 15000, 'state', 'DC', null, 'dc-medicaid', true,
 'DC has one of the most generous Medicaid eligibility thresholds in the country — childless adults qualify up to 215% FPL through the DC Healthcare Alliance. The 138% baseline used here is conservative; users between 138-215% FPL should still apply.',
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('DC SNAP', 'Food Assistance',
 'DC''s Supplemental Nutrition Assistance Program provides monthly food benefits on a DC Access Card. Administered by the Department of Human Services Economic Security Administration.',
 'Up to ~$975/month for a family of four',
 'DC households with gross monthly income at or below 200% of the federal poverty level (state-expanded threshold via BBCE)',
 '202-727-5355', 'https://dhs.dc.gov/service/snap-benefits-formerly-food-stamps',
 11676, 'state', 'DC', null, 'dc-snap', true, null,
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('DC TANF', 'Cash Assistance',
 'Monthly cash assistance for low-income DC families with minor children, plus access to employment and training services through the TANF Employment Program. Administered by the Department of Human Services.',
 'Up to ~$748/month for a family of three',
 'DC families with minor children and limited income/resources',
 '202-727-5355', 'https://dhs.dc.gov/service/tanf-benefits',
 3500, 'state', 'DC', null, 'dc-tanf', true, null,
 '{"max_monthly_income": 1300, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('DC LIHEAP (Energy Assistance)', 'Utility Assistance',
 'DC''s federally-funded LIHEAP helps qualifying households pay heating, cooling, and crisis energy bills. Administered by the Department of Energy and Environment.',
 '$300–$1,500 per year toward energy bills',
 'DC households with income at or below 60% of State Median Income (~200% FPL)',
 '202-535-2600', 'https://doee.dc.gov/service/liheap',
 1300, 'state', 'DC', null, 'dc-liheap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('DC Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for DC residents who lost their job through no fault of their own. Administered by the DC Department of Employment Services. Most claimants receive benefits for up to 26 weeks.',
 'Up to $444/week (~$23,100/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '202-724-7000', 'https://does.dc.gov/service/unemployment-compensation-process',
 13000, 'state', 'DC', null, 'dc-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('DC Office of Veterans Affairs', 'Veteran Services',
 'The DC agency that helps DC veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers. DC veterans also access the regional VA medical center directly.',
 'Free benefits counseling and emergency assistance',
 'DC veterans, active-duty service members, and their dependents',
 '202-724-5454', 'https://ova.dc.gov',
 5000, 'state', 'DC', null, 'dc-veterans-services', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('DC Department of Aging and Community Living (DACL)', 'Senior Services',
 'DACL coordinates DC''s Aging and Disability Resource Center network, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'DC residents 60 and older and their family caregivers',
 '202-724-5626', 'https://dacl.dc.gov',
 2000, 'state', 'DC', null, 'dc-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('DC 211 (Answers, Please!)', 'Information & Referral',
 'DC 211 (Answers, Please!) is the District-wide health and human services helpline operated by the Community Council for the Homeless at Friendship Place. Call 2-1-1 or visit answersplease.dc.gov to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in DC needing help finding local services',
 '211', 'https://answersplease.dc.gov',
 0, 'state', 'DC', null, 'dc-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb);
