-- migration_033: Add Minnesota, Missouri, New Mexico, New Hampshire.
--
-- 32 rows — 8 categories per state (Medicaid, SNAP, TANF, LIHEAP,
-- unemployment, veterans, aging, 211). Housing finance slot omitted
-- (see migration_028 / catalog inclusion principles in TODO.md).
--
-- All four are expansion states. Minnesota (Medical Assistance) and
-- New Mexico (Centennial Care) and New Hampshire (Granite Advantage
-- Health Care Program) were day-one ACA expansion (2014). Missouri is
-- a recent expansion: voters passed Amendment 2 in 2020 and coverage
-- took effect in 2021-2022 — the row carries an important_notes flag
-- so future annual verification re-confirms status (parallel to NC).
--
-- LIHEAPs at 60% SMI (modeled as 200% FPL with the standard SMI note):
-- Minnesota EAP, Missouri LIHEAP, New Hampshire Fuel Assistance.
-- New Mexico LIHEAP at 150% FPL (federal default — no SMI note).
--
-- SNAP BBCE thresholds (Broad-Based Categorical Eligibility):
--   MN: 200% FPL
--   NH: 185% FPL
--   NM: 165% FPL
--   MO: 130% FPL (no BBCE — Missouri uses federal default)

insert into programs (
  name, category, description, potential_benefit, who_qualifies,
  phone_number, apply_url, benefit_value, scope, state, jurisdiction_name,
  slug, is_active, important_notes, eligibility_rules
) values

-- ── MINNESOTA ───────────────────────────────────────────────────────
('Minnesota Medical Assistance (MA)', 'Health Insurance',
 'Medical Assistance is Minnesota''s Medicaid program, providing health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Minnesota expanded Medicaid for adults under the ACA in 2014. MinnesotaCare provides additional coverage for households 138-200% FPL.',
 'Full health coverage at little to no cost',
 'Minnesota adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-800-657-3739', 'https://mn.gov/dhs/people-we-serve/adults/health-care/health-care-programs/programs-and-services/medical-assistance.jsp',
 15000, 'state', 'MN', null, 'minnesota-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Minnesota SNAP', 'Food Assistance',
 'Minnesota''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by the Department of Human Services through county human services agencies.',
 'Up to ~$975/month for a family of four',
 'Minnesota households with gross monthly income at or below 200% of the federal poverty level (state-expanded threshold via BBCE)',
 '1-800-657-3698', 'https://mn.gov/dhs/people-we-serve/adults/economic-assistance/food-nutrition/programs-and-services/supplemental-nutrition-assistance-program.jsp',
 11676, 'state', 'MN', null, 'minnesota-snap', true, null,
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Minnesota Family Investment Program (MFIP)', 'Cash Assistance',
 'Monthly cash assistance for low-income Minnesota families with minor children, plus access to employment and training services. Administered by the Department of Human Services through county human services agencies.',
 'Up to ~$632/month for a family of three',
 'Minnesota families with minor children and limited income/resources',
 '1-800-657-3698', 'https://mn.gov/dhs/people-we-serve/adults/economic-assistance/income/programs-and-services/mfip.jsp',
 3500, 'state', 'MN', null, 'minnesota-mfip', true, null,
 '{"max_monthly_income": 1100, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Minnesota Energy Assistance Program (EAP)', 'Utility Assistance',
 'Minnesota''s federally-funded Energy Assistance Program helps qualifying households pay heating bills, weatherization, and crisis energy needs. Administered by the Department of Commerce through 27 Local Service Providers.',
 '$300–$1,500 per year toward heating bills',
 'Minnesota households with income at or below 60% of State Median Income (~200% FPL)',
 '1-800-657-3710', 'https://mn.gov/commerce/consumers/consumer-assistance/energy-assistance',
 1300, 'state', 'MN', null, 'minnesota-eap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Minnesota Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Minnesotans who lost their job through no fault of their own. Administered by the Department of Employment and Economic Development. Most claimants receive benefits for up to 26 weeks.',
 'Up to $890/week (~$46,300/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '651-296-3644', 'https://www.uimn.org',
 13000, 'state', 'MN', null, 'minnesota-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Minnesota Department of Veterans Affairs', 'Veteran Services',
 'The state agency that helps Minnesota veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through County Veterans Service Officers and the Minnesota Veterans Homes.',
 'Free benefits counseling plus access to state veterans homes',
 'Minnesota veterans, active-duty service members, and their dependents',
 '1-888-546-5838', 'https://mn.gov/mdva',
 5000, 'state', 'MN', null, 'minnesota-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Minnesota Board on Aging', 'Senior Services',
 'The Minnesota Board on Aging coordinates the state''s 7 Area Agencies on Aging through the Senior LinkAge Line, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Minnesotans 60 and older and their family caregivers',
 '1-800-333-2433', 'https://mn.gov/board-on-aging',
 2000, 'state', 'MN', null, 'minnesota-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Minnesota 211 (United Way)', 'Information & Referral',
 'Minnesota 211 is the statewide health and human services helpline operated by United Way of Greater Twin Cities. Call 2-1-1 or visit 211unitedway.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Minnesota needing help finding local services',
 '211', 'https://www.211unitedway.org',
 0, 'state', 'MN', null, 'minnesota-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── MISSOURI (expansion as of 2021-2022) ────────────────────────────
('MO HealthNet (Missouri Medicaid)', 'Health Insurance',
 'MO HealthNet is Missouri''s Medicaid program, providing health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Missouri voters approved Medicaid expansion via Amendment 2 in 2020, with adult coverage taking effect in 2021-2022.',
 'Full health coverage at little to no cost',
 'Missouri adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-855-373-4636', 'https://mydss.mo.gov/healthcare',
 15000, 'state', 'MO', null, 'missouri-medicaid', true,
 'Missouri voters passed Medicaid expansion in 2020 (Amendment 2); adult coverage took effect in 2021-2022. Annual verification should re-confirm status.',
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Missouri SNAP (Food Stamps)', 'Food Assistance',
 'Missouri''s Supplemental Nutrition Assistance Program provides monthly food benefits on a Missouri EBT card. Administered by the Department of Social Services Family Support Division.',
 'Up to ~$975/month for a family of four',
 'Missouri households with gross monthly income at or below 130% of the federal poverty level',
 '1-855-373-4636', 'https://mydss.mo.gov/food-assistance',
 11676, 'state', 'MO', null, 'missouri-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Missouri Temporary Assistance (TANF)', 'Cash Assistance',
 'Monthly cash assistance for low-income Missouri families with minor children, plus access to employment and training services. Administered by the Department of Social Services Family Support Division.',
 'Up to ~$292/month for a family of three',
 'Missouri families with minor children and very low income',
 '1-855-373-4636', 'https://mydss.mo.gov/temporary-assistance',
 3500, 'state', 'MO', null, 'missouri-tanf', true, null,
 '{"max_monthly_income": 750, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Missouri LIHEAP (Energy Assistance Program)', 'Utility Assistance',
 'Missouri''s federally-funded LIHEAP helps qualifying households pay heating, cooling, and crisis energy bills. Administered by the Department of Social Services Family Support Division.',
 '$300–$1,500 per year toward energy bills',
 'Missouri households with income at or below 60% of State Median Income (~200% FPL)',
 '1-855-373-4636', 'https://mydss.mo.gov/energy-assistance',
 1300, 'state', 'MO', null, 'missouri-liheap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Missouri Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Missourians who lost their job through no fault of their own. Administered by the Missouri Department of Labor Division of Employment Security. Most claimants receive benefits for up to 20 weeks.',
 'Up to $320/week (~$16,600/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-800-320-2519', 'https://labor.mo.gov/des',
 13000, 'state', 'MO', null, 'missouri-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Missouri Veterans Commission', 'Veteran Services',
 'The state agency that helps Missouri veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and seven Missouri State Veterans Homes.',
 'Free benefits counseling plus access to state veterans homes',
 'Missouri veterans, active-duty service members, and their dependents',
 '1-866-838-4636', 'https://mvc.dps.mo.gov',
 5000, 'state', 'MO', null, 'missouri-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Missouri Senior and Disability Services', 'Senior Services',
 'The Department of Health and Senior Services Division of Senior and Disability Services coordinates Missouri''s 10 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Missourians 60 and older and their family caregivers',
 '1-800-235-5503', 'https://health.mo.gov/seniors',
 2000, 'state', 'MO', null, 'missouri-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Missouri 211', 'Information & Referral',
 'Missouri 211 is the statewide health and human services helpline operated by United Way 211 Missouri. Call 2-1-1 or visit 211missouri.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Missouri needing help finding local services',
 '211', 'https://211missouri.org',
 0, 'state', 'MO', null, 'missouri-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── NEW MEXICO ──────────────────────────────────────────────────────
('Centennial Care (New Mexico Medicaid)', 'Health Insurance',
 'Centennial Care is New Mexico''s Medicaid program, providing health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. New Mexico expanded Medicaid for adults under the ACA in 2014.',
 'Full health coverage at little to no cost',
 'New Mexico adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-855-637-6574', 'https://www.hsd.state.nm.us/lookingforassistance/medical-assistance-programs',
 15000, 'state', 'NM', null, 'new-mexico-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('New Mexico SNAP', 'Food Assistance',
 'New Mexico''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by the Health Care Authority Income Support Division.',
 'Up to ~$975/month for a family of four',
 'New Mexico households with gross monthly income at or below 165% of the federal poverty level (state-expanded threshold via BBCE)',
 '1-800-283-4465', 'https://www.yes.state.nm.us',
 11676, 'state', 'NM', null, 'new-mexico-snap', true, null,
 '{"max_income_percent_fpl": 165, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('New Mexico Works (TANF)', 'Cash Assistance',
 'Monthly cash assistance for low-income New Mexico families with minor children, plus access to employment and training services. Administered by the Health Care Authority Income Support Division.',
 'Up to ~$447/month for a family of three',
 'New Mexico families with minor children and limited income/resources',
 '1-800-283-4465', 'https://www.hca.nm.gov/lookingforassistance/temporary-assistance',
 3500, 'state', 'NM', null, 'new-mexico-tanf', true, null,
 '{"max_monthly_income": 900, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('New Mexico LIHEAP', 'Utility Assistance',
 'New Mexico''s federally-funded LIHEAP helps qualifying households pay heating, cooling, and crisis energy bills. Administered by the Health Care Authority Income Support Division.',
 '$300–$1,500 per year toward energy bills',
 'New Mexico households with income at or below 150% of the federal poverty level',
 '1-800-283-4465', 'https://www.hca.nm.gov/lookingforassistance/heating-cooling-utility-assistance',
 1300, 'state', 'NM', null, 'new-mexico-liheap', true, null,
 '{"max_income_percent_fpl": 150, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('New Mexico Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for New Mexicans who lost their job through no fault of their own. Administered by the Department of Workforce Solutions. Most claimants receive benefits for up to 26 weeks.',
 'Up to $580/week (~$30,200/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-877-664-6984', 'https://www.dws.state.nm.us',
 13000, 'state', 'NM', null, 'new-mexico-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('New Mexico Department of Veterans Services', 'Veteran Services',
 'The state agency that helps New Mexico veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and the New Mexico State Veterans Home in Truth or Consequences.',
 'Free benefits counseling plus access to state veterans home',
 'New Mexico veterans, active-duty service members, and their dependents',
 '1-866-433-8387', 'https://www.nmdvs.org',
 5000, 'state', 'NM', null, 'new-mexico-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('New Mexico Aging and Long-Term Services Department (ALTSD)', 'Senior Services',
 'ALTSD coordinates New Mexico''s 6 Area Agencies on Aging through the Aging and Disability Resource Center, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'New Mexicans 60 and older and their family caregivers',
 '1-800-432-2080', 'https://www.nmaging.state.nm.us',
 2000, 'state', 'NM', null, 'new-mexico-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('New Mexico 211', 'Information & Referral',
 'New Mexico 211 is the statewide health and human services helpline operated by United Way of Central New Mexico. Call 2-1-1 or visit nm211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in New Mexico needing help finding local services',
 '211', 'https://www.nm211.org',
 0, 'state', 'NM', null, 'new-mexico-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── NEW HAMPSHIRE ───────────────────────────────────────────────────
('Granite Advantage Health Care Program (NH Medicaid)', 'Health Insurance',
 'Granite Advantage is New Hampshire''s Medicaid expansion program for adults, paired with traditional NH Medicaid for children, pregnant women, seniors, and people with disabilities. New Hampshire expanded Medicaid for adults under the ACA in 2014. Apply through NH EASY.',
 'Full health coverage at little to no cost',
 'New Hampshire adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-844-275-3447', 'https://nheasy.nh.gov',
 15000, 'state', 'NH', null, 'new-hampshire-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('New Hampshire SNAP (Food Stamps)', 'Food Assistance',
 'New Hampshire''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by the Department of Health and Human Services through NH EASY.',
 'Up to ~$975/month for a family of four',
 'New Hampshire households with gross monthly income at or below 185% of the federal poverty level (state-expanded threshold via BBCE)',
 '1-844-275-3447', 'https://www.dhhs.nh.gov/programs-services/economic-support/food-stamps',
 11676, 'state', 'NH', null, 'new-hampshire-snap', true, null,
 '{"max_income_percent_fpl": 185, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('New Hampshire Financial Assistance for Needy Families (FANF)', 'Cash Assistance',
 'Monthly cash assistance for low-income New Hampshire families with minor children, plus access to employment and training services. Administered by the Department of Health and Human Services.',
 'Up to ~$1,098/month for a family of three',
 'New Hampshire families with minor children and limited income/resources',
 '1-844-275-3447', 'https://www.dhhs.nh.gov/programs-services/economic-support/financial-assistance-families-and-children',
 3500, 'state', 'NH', null, 'new-hampshire-fanf', true, null,
 '{"max_monthly_income": 1500, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('New Hampshire Fuel Assistance Program', 'Utility Assistance',
 'New Hampshire''s federally-funded Fuel Assistance Program (LIHEAP) helps qualifying households pay heating bills and crisis energy needs. Administered by the Office of Strategic Initiatives through 6 Community Action Agencies.',
 '$300–$1,500 per year toward heating bills',
 'New Hampshire households with income at or below 60% of State Median Income (~200% FPL)',
 '603-271-2155', 'https://www.nh.gov/osi/energy/programs/fuel-assistance.htm',
 1300, 'state', 'NH', null, 'new-hampshire-fuel-assistance', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('New Hampshire Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for New Hampshirites who lost their job through no fault of their own. Administered by the New Hampshire Employment Security. Most claimants receive benefits for up to 26 weeks.',
 'Up to $427/week plus dependent allowance (~$22,200/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '603-224-3311', 'https://www.nhes.nh.gov',
 13000, 'state', 'NH', null, 'new-hampshire-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('New Hampshire Office of Veterans Services', 'Veteran Services',
 'The state agency that helps New Hampshire veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and the New Hampshire Veterans Home in Tilton.',
 'Free benefits counseling plus access to state veterans home',
 'New Hampshire veterans, active-duty service members, and their dependents',
 '603-624-9230', 'https://www.dmavs.nh.gov',
 5000, 'state', 'NH', null, 'new-hampshire-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('New Hampshire Bureau of Elderly and Adult Services (BEAS)', 'Senior Services',
 'BEAS coordinates New Hampshire''s ServiceLink Resource Center network, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'New Hampshirites 60 and older and their family caregivers',
 '1-866-634-9412', 'https://www.dhhs.nh.gov/programs-services/adult-aging-care',
 2000, 'state', 'NH', null, 'new-hampshire-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('New Hampshire 211', 'Information & Referral',
 'NH 211 is the statewide health and human services helpline operated by Granite United Way. Call 2-1-1 or visit nh211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in New Hampshire needing help finding local services',
 '211', 'https://www.nh211.org',
 0, 'state', 'NH', null, 'new-hampshire-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb);
