-- migration_029: Add Wyoming, Massachusetts, Pennsylvania, New Jersey, North Carolina.
--
-- 40 rows — 8 categories per state (Medicaid, SNAP, TANF, LIHEAP,
-- unemployment, veterans, aging, 211). The state housing finance slot is
-- deliberately omitted (see migration_028 / catalog inclusion principles
-- in TODO.md).
--
-- Wyoming is non-expansion — Wyoming Medicaid is gated by
-- ["single_parent","pregnant","disability"] like FL/AL/GA/MS/KS/TN.
-- Massachusetts (MassHealth), Pennsylvania (Medical Assistance), New Jersey
-- (NJ FamilyCare), and North Carolina (NC Medicaid) are all expansion
-- states with no required_situations gate.
--
-- Note: NC expanded Medicaid in December 2023, moving from non-expansion
-- to expansion. Annual verification should re-confirm status.
--
-- LIHEAPs at 60% SMI (modeled as 200% FPL with the standard SMI note):
-- Wyoming LIEAP, Massachusetts Fuel Assistance, NJ LIHEAP. PA LIHEAP and
-- NC LIEAP follow the federal default of 150% FPL and get no SMI note.

insert into programs (
  name, category, description, potential_benefit, who_qualifies,
  phone_number, apply_url, benefit_value, scope, state, jurisdiction_name,
  slug, is_active, important_notes, eligibility_rules
) values

-- ── WYOMING (non-expansion) ─────────────────────────────────────────
('Wyoming Medicaid', 'Health Insurance',
 'Wyoming Medicaid provides health coverage including doctor visits, hospital care, prescriptions, and preventive services. Wyoming did not expand Medicaid for non-disabled adults, so most adult coverage is limited to parents of minor children, pregnant women, and people with disabilities.',
 'Full health coverage at little to no cost',
 'Low-income parents of minor children, pregnant women, people with disabilities, seniors, and children',
 '1-855-294-2127', 'https://health.wyo.gov/healthcarefin/medicaid',
 15000, 'state', 'WY', null, 'wyoming-medicaid', true,
 'Wyoming did not expand Medicaid. Most adults without children, disability, or pregnancy do not qualify regardless of income.',
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": ["single_parent", "pregnant", "disability"]}'::jsonb),
('Wyoming SNAP', 'Food Assistance',
 'Wyoming''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by the Wyoming Department of Family Services.',
 'Up to ~$975/month for a family of four',
 'Wyoming households with gross monthly income at or below 130% of the federal poverty level',
 '1-800-457-3659', 'https://dfs.wyo.gov/assistance-programs/food-stamps-snap',
 11676, 'state', 'WY', null, 'wyoming-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Wyoming POWER (TANF)', 'Cash Assistance',
 'Personal Opportunities With Employment Responsibilities — monthly cash assistance for low-income Wyoming families with minor children, plus access to employment and training services. Administered by the Department of Family Services.',
 'Up to ~$671/month for a family of three',
 'Wyoming families with minor children and limited income/resources',
 '1-800-457-3659', 'https://dfs.wyo.gov/assistance-programs/temporary-assistance-tanf-power',
 3500, 'state', 'WY', null, 'wyoming-power', true, null,
 '{"max_monthly_income": 1200, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Wyoming LIEAP', 'Utility Assistance',
 'Wyoming''s federally-funded Low-Income Energy Assistance Program helps qualifying households pay heating bills and crisis energy needs. Administered by the Department of Family Services.',
 '$300–$1,500 per year toward heating bills',
 'Wyoming households with income at or below 60% of State Median Income (~200% FPL)',
 '1-800-246-4221', 'https://dfs.wyo.gov/assistance-programs/lieap',
 1300, 'state', 'WY', null, 'wyoming-lieap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Wyoming Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Wyomingites who lost their job through no fault of their own. Administered by the Wyoming Department of Workforce Services. Most claimants receive benefits for up to 26 weeks.',
 'Up to $595/week (~$30,900/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '307-473-3789', 'https://dws.wyo.gov/dws-division/unemployment-insurance',
 13000, 'state', 'WY', null, 'wyoming-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Wyoming Veterans Commission', 'Veteran Services',
 'The state agency that helps Wyoming veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and the Wyoming Veterans Home in Buffalo.',
 'Free benefits counseling plus access to state veterans home',
 'Wyoming veterans, active-duty service members, and their dependents',
 '307-777-8152', 'https://wvc.wyo.gov',
 5000, 'state', 'WY', null, 'wyoming-veterans-commission', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Wyoming Aging Division', 'Senior Services',
 'The Wyoming Department of Health Aging Division coordinates the state''s 2 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Wyomingites 60 and older and their family caregivers',
 '1-800-442-2766', 'https://health.wyo.gov/aging',
 2000, 'state', 'WY', null, 'wyoming-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Wyoming 211', 'Information & Referral',
 'Wyoming 211 is the statewide health and human services helpline operated by United Way of the Greater Capital Area. Call 2-1-1 or visit wyoming211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Wyoming needing help finding local services',
 '211', 'https://wyoming211.org',
 0, 'state', 'WY', null, 'wyoming-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── MASSACHUSETTS ───────────────────────────────────────────────────
('MassHealth (Massachusetts Medicaid)', 'Health Insurance',
 'MassHealth is Massachusetts''s combined Medicaid and CHIP program, providing health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Massachusetts has had universal-style coverage since 2006 and expanded under the ACA.',
 'Full health coverage at little to no cost',
 'Massachusetts adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-800-841-2900', 'https://www.mass.gov/masshealth',
 15000, 'state', 'MA', null, 'massachusetts-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Massachusetts SNAP', 'Food Assistance',
 'Massachusetts''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by the Department of Transitional Assistance (DTA).',
 'Up to ~$975/month for a family of four',
 'Massachusetts households with gross monthly income at or below 200% of the federal poverty level (state-expanded threshold)',
 '1-877-382-2363', 'https://www.mass.gov/snap-benefits-formerly-food-stamps',
 11676, 'state', 'MA', null, 'massachusetts-snap', true, null,
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Massachusetts TAFDC (Transitional Aid to Families with Dependent Children)', 'Cash Assistance',
 'Monthly cash assistance for low-income Massachusetts families with minor children, plus access to employment and training services. Administered by the Department of Transitional Assistance.',
 'Up to ~$783/month for a family of three',
 'Massachusetts families with minor children and limited income/resources',
 '1-877-382-2363', 'https://www.mass.gov/tafdc',
 3500, 'state', 'MA', null, 'massachusetts-tafdc', true, null,
 '{"max_monthly_income": 1500, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Massachusetts Fuel Assistance (LIHEAP)', 'Utility Assistance',
 'Massachusetts''s federally-funded Low Income Home Energy Assistance Program helps qualifying households pay heating bills and crisis energy needs. Administered by the Department of Housing and Community Development through 21 Local Administering Agencies.',
 '$300–$1,500 per year toward heating bills',
 'Massachusetts households with income at or below 60% of State Median Income (~200% FPL)',
 '1-800-632-8175', 'https://www.mass.gov/how-to/apply-for-fuel-assistance-liheap',
 1300, 'state', 'MA', null, 'massachusetts-fuel-assistance', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Massachusetts Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Massachusetts workers who lost their job through no fault of their own. Administered by the Department of Unemployment Assistance. Most claimants receive benefits for up to 30 weeks.',
 'Up to $1,033/week (~$53,700/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-877-626-6800', 'https://www.mass.gov/unemployment-insurance-ui-online',
 13000, 'state', 'MA', null, 'massachusetts-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Massachusetts Executive Office of Veterans'' Services', 'Veteran Services',
 'Massachusetts''s standalone Executive Office of Veterans'' Services helps veterans access state and federal benefits — including Chapter 115 needs-based cash and medical aid, the Welcome Home Bonus, and access to two state veterans homes — through 240+ municipal Veterans'' Service Officers.',
 'Free benefits counseling plus state Chapter 115 cash/medical aid',
 'Massachusetts veterans, active-duty service members, and their dependents',
 '617-210-5480', 'https://www.mass.gov/orgs/executive-office-of-veterans-services',
 5000, 'state', 'MA', null, 'massachusetts-veterans-services', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Massachusetts Executive Office of Aging & Independence', 'Senior Services',
 'Massachusetts''s Executive Office of Aging & Independence (formerly Elder Affairs) coordinates the state''s 25 Aging Services Access Points and 23 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Massachusetts residents 60 and older and their family caregivers',
 '1-800-243-4636', 'https://www.mass.gov/orgs/executive-office-of-aging-independence',
 2000, 'state', 'MA', null, 'massachusetts-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Mass 2-1-1', 'Information & Referral',
 'Mass 2-1-1 is the statewide health and human services helpline operated by United Ways of Massachusetts. Call 2-1-1 or visit mass211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Massachusetts needing help finding local services',
 '211', 'https://mass211.org',
 0, 'state', 'MA', null, 'massachusetts-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── PENNSYLVANIA ────────────────────────────────────────────────────
('Pennsylvania Medical Assistance (Medicaid)', 'Health Insurance',
 'Pennsylvania Medical Assistance is the state Medicaid program, providing health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Pennsylvania expanded Medicaid for adults under the ACA. Apply through COMPASS.',
 'Full health coverage at little to no cost',
 'Pennsylvania adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-866-550-4355', 'https://www.compass.state.pa.us',
 15000, 'state', 'PA', null, 'pennsylvania-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Pennsylvania SNAP', 'Food Assistance',
 'Pennsylvania''s Supplemental Nutrition Assistance Program provides monthly food benefits on an Access EBT card. Administered by the Department of Human Services through COMPASS.',
 'Up to ~$975/month for a family of four',
 'Pennsylvania households with gross monthly income at or below 200% of the federal poverty level (state-expanded threshold)',
 '1-800-692-7462', 'https://www.dhs.pa.gov/snap',
 11676, 'state', 'PA', null, 'pennsylvania-snap', true, null,
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Pennsylvania TANF (Temporary Assistance for Needy Families)', 'Cash Assistance',
 'Monthly cash assistance for low-income Pennsylvania families with minor children, plus access to employment and training services. Administered by the Department of Human Services.',
 'Up to ~$403/month for a family of three',
 'Pennsylvania families with minor children and limited income/resources',
 '1-800-692-7462', 'https://www.dhs.pa.gov/Services/Assistance/Pages/TANF.aspx',
 3500, 'state', 'PA', null, 'pennsylvania-tanf', true, null,
 '{"max_monthly_income": 850, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Pennsylvania LIHEAP', 'Utility Assistance',
 'Pennsylvania''s federally-funded LIHEAP helps qualifying households pay heating bills, crisis energy needs, and weatherization. Administered by the Department of Human Services through COMPASS.',
 '$300–$1,500 per year toward heating bills',
 'Pennsylvania households with income at or below 150% of the federal poverty level',
 '1-866-857-7095', 'https://www.dhs.pa.gov/Services/Assistance/Pages/LIHEAP.aspx',
 1300, 'state', 'PA', null, 'pennsylvania-liheap', true, null,
 '{"max_income_percent_fpl": 150, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Pennsylvania Unemployment Compensation', 'Income Assistance',
 'Weekly cash benefits for Pennsylvanians who lost their job through no fault of their own. Administered by the Department of Labor & Industry. Most claimants receive benefits for up to 26 weeks.',
 'Up to $605/week plus dependent allowance (~$31,500/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-888-313-7284', 'https://www.uc.pa.gov',
 13000, 'state', 'PA', null, 'pennsylvania-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Pennsylvania Department of Military and Veterans Affairs (DMVA)', 'Veteran Services',
 'The state agency that helps Pennsylvania veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through County Directors of Veterans Affairs and six Pennsylvania State Veterans Homes.',
 'Free benefits counseling plus access to state veterans homes',
 'Pennsylvania veterans, active-duty service members, and their dependents',
 '1-800-547-2838', 'https://www.dmva.pa.gov',
 5000, 'state', 'PA', null, 'pennsylvania-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Pennsylvania Department of Aging', 'Senior Services',
 'Pennsylvania''s Department of Aging coordinates the state''s 52 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, prescription assistance (PACE/PACENET), and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Pennsylvanians 60 and older and their family caregivers',
 '717-783-1550', 'https://www.aging.pa.gov',
 2000, 'state', 'PA', null, 'pennsylvania-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Pennsylvania 211', 'Information & Referral',
 'PA 211 is the statewide health and human services helpline operated by United Way of Pennsylvania through six regional 211 contact centers. Call 2-1-1 or visit pa211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Pennsylvania needing help finding local services',
 '211', 'https://pa211.org',
 0, 'state', 'PA', null, 'pennsylvania-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── NEW JERSEY ──────────────────────────────────────────────────────
('NJ FamilyCare (New Jersey Medicaid)', 'Health Insurance',
 'NJ FamilyCare is New Jersey''s combined Medicaid and CHIP program, providing health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. New Jersey expanded Medicaid for adults under the ACA.',
 'Full health coverage at little to no cost',
 'New Jersey adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-800-701-0710', 'https://www.njfamilycare.org',
 15000, 'state', 'NJ', null, 'new-jersey-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('New Jersey SNAP (NJ SNAP)', 'Food Assistance',
 'NJ SNAP provides monthly food benefits on a Families First EBT card. Administered by the Department of Human Services Division of Family Development through county welfare agencies.',
 'Up to ~$975/month for a family of four',
 'New Jersey households with gross monthly income at or below 185% of the federal poverty level (state-expanded threshold)',
 '1-800-687-9512', 'https://www.nj.gov/humanservices/njsnap',
 11676, 'state', 'NJ', null, 'new-jersey-snap', true, null,
 '{"max_income_percent_fpl": 185, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('New Jersey WorkFirst (TANF)', 'Cash Assistance',
 'Monthly cash assistance for low-income New Jersey families with minor children, plus access to employment and training services. Administered by the Department of Human Services through county welfare agencies.',
 'Up to ~$559/month for a family of three',
 'New Jersey families with minor children and limited income/resources',
 '1-800-792-9773', 'https://www.nj.gov/humanservices/dfd/programs/workfirstnj',
 3500, 'state', 'NJ', null, 'new-jersey-workfirst', true, null,
 '{"max_monthly_income": 1000, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('New Jersey LIHEAP', 'Utility Assistance',
 'New Jersey''s federally-funded Low Income Home Energy Assistance Program helps qualifying households pay heating, cooling, and crisis energy bills. Administered by the Department of Community Affairs.',
 '$300–$1,500 per year toward energy bills',
 'New Jersey households with income at or below 60% of State Median Income (~200% FPL)',
 '1-800-510-3102', 'https://www.nj.gov/dca/dhcr/offices/hea.shtml',
 1300, 'state', 'NJ', null, 'new-jersey-liheap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('New Jersey Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for New Jerseyans who lost their job through no fault of their own. Administered by the Department of Labor and Workforce Development. Most claimants receive benefits for up to 26 weeks.',
 'Up to $854/week (~$44,400/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '732-761-2020', 'https://myunemployment.nj.gov',
 13000, 'state', 'NJ', null, 'new-jersey-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('New Jersey Department of Military and Veterans Affairs', 'Veteran Services',
 'The state agency that helps New Jersey veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and three New Jersey Veterans Memorial Homes.',
 'Free benefits counseling plus access to state veterans memorial homes',
 'New Jersey veterans, active-duty service members, and their dependents',
 '1-888-865-8387', 'https://www.nj.gov/military/veterans',
 5000, 'state', 'NJ', null, 'new-jersey-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('New Jersey Division of Aging Services', 'Senior Services',
 'NJ''s Division of Aging Services, within the Department of Human Services, coordinates the state''s 21 county-based Area Agencies on Aging through the NJSave portal, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'New Jerseyans 60 and older and their family caregivers',
 '1-877-222-3737', 'https://www.nj.gov/humanservices/doas',
 2000, 'state', 'NJ', null, 'new-jersey-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('NJ 211', 'Information & Referral',
 'NJ 211 is the statewide health and human services helpline operated by NJ 211 Partnership. Call 2-1-1 or visit nj211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in New Jersey needing help finding local services',
 '211', 'https://www.nj211.org',
 0, 'state', 'NJ', null, 'new-jersey-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── NORTH CAROLINA (expansion as of December 2023) ──────────────────
('North Carolina Medicaid', 'Health Insurance',
 'North Carolina Medicaid provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. North Carolina expanded Medicaid for adults in December 2023 under the ACA. Apply through ePASS or your county DSS.',
 'Full health coverage at little to no cost',
 'North Carolina adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-888-245-0179', 'https://medicaid.ncdhhs.gov',
 15000, 'state', 'NC', null, 'north-carolina-medicaid', true,
 'North Carolina expanded Medicaid in December 2023. Adults aged 19-64 at or below 138% FPL now qualify regardless of parental, pregnancy, or disability status.',
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('North Carolina Food and Nutrition Services (SNAP)', 'Food Assistance',
 'North Carolina''s Supplemental Nutrition Assistance Program (Food and Nutrition Services) provides monthly food benefits on an EBT card. Administered by the Department of Health and Human Services through county DSS offices.',
 'Up to ~$975/month for a family of four',
 'North Carolina households with gross monthly income at or below 200% of the federal poverty level (state-expanded threshold)',
 '1-800-662-7030', 'https://www.ncdhhs.gov/divisions/social-services/food-and-nutrition-services-food-stamps',
 11676, 'state', 'NC', null, 'north-carolina-snap', true, null,
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('North Carolina Work First (TANF)', 'Cash Assistance',
 'Monthly cash assistance for low-income North Carolina families with minor children, plus access to employment and training services. Administered by the Department of Health and Human Services through county DSS offices.',
 'Up to ~$272/month for a family of three',
 'North Carolina families with minor children and very low income',
 '1-800-662-7030', 'https://www.ncdhhs.gov/divisions/social-services/work-first',
 3500, 'state', 'NC', null, 'north-carolina-work-first', true, null,
 '{"max_monthly_income": 750, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('North Carolina Energy Assistance (LIEAP/CIP)', 'Utility Assistance',
 'North Carolina''s federally-funded Low Income Energy Assistance Program (LIEAP) and Crisis Intervention Program (CIP) help qualifying households pay heating, cooling, and crisis energy bills. Administered by the Department of Health and Human Services through county DSS offices.',
 '$300–$1,500 per year toward energy bills',
 'North Carolina households with income at or below 150% of the federal poverty level',
 '1-800-662-7030', 'https://www.ncdhhs.gov/divisions/social-services/energy-assistance',
 1300, 'state', 'NC', null, 'north-carolina-lieap', true, null,
 '{"max_income_percent_fpl": 150, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('North Carolina Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for North Carolinians who lost their job through no fault of their own. Administered by the Division of Employment Security. Most claimants receive benefits for up to 12 weeks (longest period in the country at the lower bound).',
 'Up to $600/week (~$31,200/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-888-737-0259', 'https://des.nc.gov',
 13000, 'state', 'NC', null, 'north-carolina-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('North Carolina Department of Military and Veterans Affairs', 'Veteran Services',
 'The state agency that helps North Carolina veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and four North Carolina State Veterans Homes.',
 'Free benefits counseling plus access to state veterans homes',
 'North Carolina veterans, active-duty service members, and their dependents',
 '1-844-624-8387', 'https://www.milvets.nc.gov',
 5000, 'state', 'NC', null, 'north-carolina-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('North Carolina Division of Aging', 'Senior Services',
 'The Division of Aging within the NC Department of Health and Human Services coordinates the state''s 16 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'North Carolinians 60 and older and their family caregivers',
 '919-855-3400', 'https://www.ncdhhs.gov/divisions/aging',
 2000, 'state', 'NC', null, 'north-carolina-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('NC 211', 'Information & Referral',
 'NC 211 is the statewide health and human services helpline operated by United Way of North Carolina. Call 2-1-1 or visit nc211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in North Carolina needing help finding local services',
 '211', 'https://nc211.org',
 0, 'state', 'NC', null, 'north-carolina-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb);
