-- migration_025: Add Colorado, Connecticut, Delaware, Idaho, Indiana.
--
-- 45 rows (9 per state). All five are Medicaid expansion states, so
-- Medicaid is gated at 138% FPL with no required_situations.
--
-- Indiana Medicaid name references both "Indiana Medicaid" and the
-- program's brand "Healthy Indiana Plan" so it's findable either way
-- (same pattern as Arkansas ARHOME).
--
-- Four LIHEAPs (CO/CT/DE/IN) carry a uniform important_notes explaining
-- that the state actually uses 60% SMI, not the federal 150% FPL default
-- — what we're modelling is an approximation. Idaho follows federal default
-- and gets no note.

insert into programs (
  name, category, description, potential_benefit, who_qualifies,
  phone_number, apply_url, benefit_value, scope, state, jurisdiction_name,
  slug, is_active, important_notes, eligibility_rules
) values

-- ── COLORADO ────────────────────────────────────────────────────────
('Health First Colorado (Colorado Medicaid)', 'Health Insurance',
 'Health First Colorado is the state Medicaid program, providing health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Colorado expanded Medicaid for adults under the ACA. Apply through PEAK.',
 'Full health coverage at little to no cost',
 'Colorado adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-800-221-3943', 'https://co.gov/peak',
 15000, 'state', 'CO', null, 'colorado-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Colorado SNAP', 'Food Assistance',
 'Colorado''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by county human services departments through the PEAK portal.',
 'Up to ~$975/month for a family of four',
 'Colorado households with gross monthly income at or below 130% of the federal poverty level',
 '1-800-221-3943', 'https://co.gov/peak',
 11676, 'state', 'CO', null, 'colorado-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Colorado Works (TANF)', 'Cash Assistance',
 'Monthly cash assistance for low-income Colorado families with minor children, plus access to employment and training services. Administered by the Colorado Department of Human Services through county offices.',
 'Up to ~$508/month for a family of three',
 'Colorado families with minor children and limited income/resources',
 '1-800-221-3943', 'https://co.gov/peak',
 3500, 'state', 'CO', null, 'colorado-works', true, null,
 '{"max_monthly_income": 1000, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Colorado Housing and Finance Authority (CHFA)', 'Housing Assistance',
 'CHFA administers Colorado''s first-time and qualifying repeat homebuyer programs, with down-payment and closing-cost assistance plus below-market mortgage rates. Income and home-price limits vary by county.',
 'Down-payment assistance plus below-market mortgage rates',
 'Colorado homebuyers meeting CHFA program income and home-price limits',
 '1-800-877-2432', 'https://www.chfainfo.com',
 10000, 'state', 'CO', null, 'colorado-chfa', true, null,
 '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb),
('Colorado Low-income Energy Assistance Program (LEAP)', 'Utility Assistance',
 'Colorado''s federally-funded LIHEAP helps qualifying households pay heating bills and crisis energy needs. Administered by CDHS through community-action agencies.',
 '$300–$1,500 per year toward heating bills',
 'Colorado households with income at or below 60% of State Median Income (~200% FPL)',
 '1-866-432-8435', 'https://cdhs.colorado.gov/leap',
 1300, 'state', 'CO', null, 'colorado-leap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Colorado Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Coloradans who lost their job through no fault of their own. Administered by the Colorado Department of Labor and Employment. Most claimants receive benefits for up to 26 weeks.',
 'Up to $781/week (~$40,600/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-303-318-9000', 'https://cdle.colorado.gov',
 13000, 'state', 'CO', null, 'colorado-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Colorado Department of Military and Veterans Affairs', 'Veteran Services',
 'The state agency that helps Colorado veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through veteran service officers and the Colorado State Veterans Trust Fund.',
 'Free benefits counseling plus access to state veterans homes',
 'Colorado veterans, active-duty service members, and their dependents',
 '1-303-284-6077', 'https://vets.colorado.gov',
 5000, 'state', 'CO', null, 'colorado-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Colorado State Unit on Aging', 'Senior Services',
 'Colorado''s State Unit on Aging coordinates the state''s 16 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Coloradans 60 and older and their family caregivers',
 '1-844-265-2372', 'https://cdhs.colorado.gov/older-adults',
 2000, 'state', 'CO', null, 'colorado-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Colorado 211', 'Information & Referral',
 'Colorado 211 is the statewide health and human services helpline. Call 2-1-1 or visit 211colorado.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Colorado needing help finding local services',
 '211', 'https://www.211colorado.org',
 0, 'state', 'CO', null, 'colorado-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── CONNECTICUT ─────────────────────────────────────────────────────
('HUSKY Health (Connecticut Medicaid)', 'Health Insurance',
 'HUSKY Health is the state Medicaid program, providing health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Connecticut expanded Medicaid for adults under the ACA. Apply through ConneCT.',
 'Full health coverage at little to no cost',
 'Connecticut adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-877-284-8759', 'https://www.connect.ct.gov',
 15000, 'state', 'CT', null, 'connecticut-husky', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Connecticut SNAP', 'Food Assistance',
 'Connecticut''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by the Department of Social Services through ConneCT.',
 'Up to ~$975/month for a family of four',
 'Connecticut households with gross monthly income at or below 130% of the federal poverty level',
 '1-877-284-8759', 'https://www.connect.ct.gov',
 11676, 'state', 'CT', null, 'connecticut-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Connecticut Temporary Family Assistance (TFA)', 'Cash Assistance',
 'Monthly cash assistance for low-income Connecticut families with minor children, plus access to employment and training services. Connecticut TFA benefits are among the more generous in the nation.',
 'Up to ~$725/month for a family of three',
 'Connecticut families with minor children and limited income/resources',
 '1-877-284-8759', 'https://www.connect.ct.gov',
 3500, 'state', 'CT', null, 'connecticut-tfa', true, null,
 '{"max_monthly_income": 1500, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Connecticut Housing Finance Authority (CHFA)', 'Housing Assistance',
 'CHFA administers Connecticut''s first-time homebuyer programs, with down-payment assistance and below-market mortgage rates. Income and home-price limits vary by city.',
 'Down-payment assistance plus below-market mortgage rates',
 'Connecticut homebuyers meeting CHFA program income and home-price limits',
 '1-860-721-9501', 'https://www.chfa.org',
 10000, 'state', 'CT', null, 'connecticut-chfa', true, null,
 '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb),
('Connecticut Energy Assistance Program (CEAP)', 'Utility Assistance',
 'Connecticut''s federally-funded LIHEAP helps qualifying households pay heating bills and crisis energy needs. Administered by the Department of Social Services through Community Action Agencies.',
 '$300–$1,500 per year toward heating bills',
 'Connecticut households with income at or below 60% of State Median Income (~200% FPL)',
 '1-860-424-5610', 'https://portal.ct.gov/dss/economic-security/winter-heating-assistance',
 1300, 'state', 'CT', null, 'connecticut-ceap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Connecticut Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Connecticuters who lost their job through no fault of their own. Administered by the Connecticut Department of Labor. Most claimants receive benefits for up to 26 weeks.',
 'Up to $703/week (~$36,500/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-860-263-6000', 'https://www.ctdol.state.ct.us',
 13000, 'state', 'CT', null, 'connecticut-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Connecticut Department of Veterans Affairs', 'Veteran Services',
 'The state agency that helps Connecticut veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and the Veterans Healthcare and Long-Term Care Center.',
 'Free benefits counseling plus access to state veterans home and healthcare',
 'Connecticut veterans, active-duty service members, and their dependents',
 '1-866-928-8387', 'https://portal.ct.gov/dva',
 5000, 'state', 'CT', null, 'connecticut-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Connecticut Aging and Disability Services', 'Senior Services',
 'Connecticut''s Department of Aging and Disability Services administers the statewide Aging and Disability Resource Center network, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Connecticuters 60 and older and their family caregivers',
 '1-860-424-5277', 'https://portal.ct.gov/aging-and-disability',
 2000, 'state', 'CT', null, 'connecticut-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Connecticut 211', 'Information & Referral',
 'Connecticut 211 is the statewide health and human services helpline operated by United Way of Connecticut. Call 2-1-1 or visit 211ct.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Connecticut needing help finding local services',
 '211', 'https://www.211ct.org',
 0, 'state', 'CT', null, 'connecticut-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── DELAWARE ────────────────────────────────────────────────────────
('Delaware Medicaid', 'Health Insurance',
 'Delaware Medicaid provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Delaware expanded Medicaid for adults under the ACA. Apply through ASSIST.',
 'Full health coverage at little to no cost',
 'Delaware adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-800-372-2022', 'https://assist.dhss.delaware.gov',
 15000, 'state', 'DE', null, 'delaware-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Delaware SNAP', 'Food Assistance',
 'Delaware''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by the Department of Health and Social Services through ASSIST.',
 'Up to ~$975/month for a family of four',
 'Delaware households with gross monthly income at or below 130% of the federal poverty level',
 '1-800-372-2022', 'https://assist.dhss.delaware.gov',
 11676, 'state', 'DE', null, 'delaware-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Delaware TANF', 'Cash Assistance',
 'Monthly cash assistance for low-income Delaware families with minor children, plus access to employment and training services. Administered by the Department of Health and Social Services.',
 'Up to ~$338/month for a family of three',
 'Delaware families with minor children and limited income/resources',
 '1-800-372-2022', 'https://assist.dhss.delaware.gov',
 3500, 'state', 'DE', null, 'delaware-tanf', true, null,
 '{"max_monthly_income": 700, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Delaware State Housing Authority (DSHA)', 'Housing Assistance',
 'DSHA administers Delaware''s first-time homebuyer programs, with down-payment assistance and below-market mortgage rates. Income and home-price limits vary by county.',
 'Down-payment assistance plus below-market mortgage rates',
 'Delaware homebuyers meeting DSHA program income and home-price limits',
 '1-888-363-8808', 'https://destatehousing.com',
 10000, 'state', 'DE', null, 'delaware-dsha', true, null,
 '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb),
('Delaware Energy Assistance Program (DEAP)', 'Utility Assistance',
 'Delaware''s federally-funded LIHEAP helps qualifying households pay heating bills and crisis energy needs. Administered by the Department of Health and Social Services through Catholic Charities.',
 '$300–$1,500 per year toward heating bills',
 'Delaware households with income at or below 60% of State Median Income (~200% FPL)',
 '1-302-654-9295', 'https://dhss.delaware.gov/dhss/dssc/liheap.html',
 1300, 'state', 'DE', null, 'delaware-liheap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Delaware Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Delawareans who lost their job through no fault of their own. Administered by the Delaware Department of Labor. Most claimants receive benefits for up to 26 weeks.',
 'Up to $450/week (~$23,400/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-302-761-8446', 'https://labor.delaware.gov',
 13000, 'state', 'DE', null, 'delaware-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Delaware Commission of Veterans Affairs', 'Veteran Services',
 'The state agency that helps Delaware veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and the Delaware Veterans Home.',
 'Free benefits counseling plus access to state veterans home',
 'Delaware veterans, active-duty service members, and their dependents',
 '1-302-225-3600', 'https://vets.delaware.gov',
 5000, 'state', 'DE', null, 'delaware-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Delaware Division of Services for Aging and Adults with Physical Disabilities (DSAAPD)', 'Senior Services',
 'DSAAPD administers Delaware''s aging services, connecting seniors and adults with physical disabilities to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Delawareans 60 and older and their family caregivers',
 '1-800-223-9074', 'https://dhss.delaware.gov/dsaapd',
 2000, 'state', 'DE', null, 'delaware-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Delaware 211', 'Information & Referral',
 'Delaware 211 is the statewide health and human services helpline operated by United Way of Delaware. Call 2-1-1 or visit delaware211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Delaware needing help finding local services',
 '211', 'https://delaware211.org',
 0, 'state', 'DE', null, 'delaware-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── IDAHO ───────────────────────────────────────────────────────────
('Idaho Medicaid', 'Health Insurance',
 'Idaho Medicaid provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Idaho expanded Medicaid for adults in 2020 under the ACA. Apply through idalink.',
 'Full health coverage at little to no cost',
 'Idaho adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-877-456-1233', 'https://idalink.idaho.gov',
 15000, 'state', 'ID', null, 'idaho-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Idaho Food Stamps (SNAP)', 'Food Assistance',
 'Idaho''s Supplemental Nutrition Assistance Program provides monthly food benefits on a Quest card. Administered by the Department of Health and Welfare through idalink.',
 'Up to ~$975/month for a family of four',
 'Idaho households with gross monthly income at or below 130% of the federal poverty level',
 '1-877-456-1233', 'https://idalink.idaho.gov',
 11676, 'state', 'ID', null, 'idaho-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Idaho Temporary Assistance for Families in Idaho (TAFI)', 'Cash Assistance',
 'Monthly cash assistance for low-income Idaho families with minor children, plus access to employment and training services. Administered by the Department of Health and Welfare.',
 'Up to ~$309/month for a family of three',
 'Idaho families with minor children and very low income',
 '1-877-456-1233', 'https://idalink.idaho.gov',
 3500, 'state', 'ID', null, 'idaho-tafi', true, null,
 '{"max_monthly_income": 700, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Idaho Housing and Finance Association (IHFA)', 'Housing Assistance',
 'IHFA administers Idaho''s first-time homebuyer programs, with down-payment assistance and below-market mortgage rates. Income and home-price limits vary by county.',
 'Down-payment assistance plus below-market mortgage rates',
 'Idaho homebuyers meeting IHFA program income and home-price limits',
 '1-855-505-4700', 'https://www.idahohousing.com',
 10000, 'state', 'ID', null, 'idaho-housing-finance', true, null,
 '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb),
('Idaho LIHEAP / Energy Assistance', 'Utility Assistance',
 'Idaho''s federally-funded Low-Income Home Energy Assistance Program helps qualifying households pay heating bills and crisis energy needs. Administered by the Department of Health and Welfare through Community Action Partnership.',
 '$300–$1,500 per year toward heating bills',
 'Idaho households with income at or below 150% of the federal poverty level',
 '1-877-456-1233', 'https://healthandwelfare.idaho.gov/services-programs/financial-help/energy-assistance-program',
 1300, 'state', 'ID', null, 'idaho-liheap', true, null,
 '{"max_income_percent_fpl": 150, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Idaho Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Idahoans who lost their job through no fault of their own. Administered by the Idaho Department of Labor. Most claimants receive benefits for up to 26 weeks.',
 'Up to $532/week (~$27,700/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-208-332-8942', 'https://www.labor.idaho.gov',
 13000, 'state', 'ID', null, 'idaho-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Idaho Division of Veterans Services', 'Veteran Services',
 'The state agency that helps Idaho veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and three Idaho Veterans Homes.',
 'Free benefits counseling plus access to state veterans homes',
 'Idaho veterans, active-duty service members, and their dependents',
 '1-208-577-2310', 'https://veterans.idaho.gov',
 5000, 'state', 'ID', null, 'idaho-veterans-services', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Idaho Commission on Aging', 'Senior Services',
 'Idaho''s Commission on Aging coordinates the state''s six Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Idahoans 60 and older and their family caregivers',
 '1-208-334-3833', 'https://aging.idaho.gov',
 2000, 'state', 'ID', null, 'idaho-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Idaho 211 (CareLine)', 'Information & Referral',
 'Idaho 211 (CareLine) is the statewide health and human services helpline operated by the Idaho Department of Health and Welfare. Call 2-1-1 or 1-800-926-2588 to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential.',
 'Free referral to local assistance programs',
 'Anyone in Idaho needing help finding local services',
 '211', 'https://healthandwelfare.idaho.gov/services-programs/211',
 0, 'state', 'ID', null, 'idaho-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── INDIANA ─────────────────────────────────────────────────────────
('Indiana Medicaid (Healthy Indiana Plan)', 'Health Insurance',
 'Indiana Medicaid, primarily delivered through the Healthy Indiana Plan (HIP) for adults, provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Indiana expanded Medicaid via HIP under the ACA.',
 'Full health coverage at little to no cost',
 'Indiana adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-877-438-4479', 'https://www.in.gov/fssa/hip/',
 15000, 'state', 'IN', null, 'indiana-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Indiana SNAP', 'Food Assistance',
 'Indiana''s Supplemental Nutrition Assistance Program provides monthly food benefits on a Hoosier Works EBT card. Administered by the Family and Social Services Administration through DFR.',
 'Up to ~$975/month for a family of four',
 'Indiana households with gross monthly income at or below 130% of the federal poverty level',
 '1-800-403-0864', 'https://fssabenefits.in.gov',
 11676, 'state', 'IN', null, 'indiana-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Indiana TANF', 'Cash Assistance',
 'Monthly cash assistance for low-income Indiana families with minor children, plus access to employment and training services. Administered by the Family and Social Services Administration through DFR.',
 'Up to ~$346/month for a family of three',
 'Indiana families with minor children and very low income',
 '1-800-403-0864', 'https://fssabenefits.in.gov',
 3500, 'state', 'IN', null, 'indiana-tanf', true, null,
 '{"max_monthly_income": 700, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Indiana Housing and Community Development Authority (IHCDA)', 'Housing Assistance',
 'IHCDA administers Indiana''s first-time homebuyer programs (Helping to Own, Next Home, Mortgage Credit Certificate), with down-payment assistance and below-market mortgage rates. Income and home-price limits vary by county.',
 'Down-payment assistance plus below-market mortgage rates',
 'Indiana homebuyers meeting IHCDA program income and home-price limits',
 '1-317-232-7777', 'https://www.in.gov/ihcda',
 10000, 'state', 'IN', null, 'indiana-ihcda', true, null,
 '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb),
('Indiana Energy Assistance Program (EAP)', 'Utility Assistance',
 'Indiana''s federally-funded LIHEAP helps qualifying households pay heating bills and crisis energy needs. Administered by IHCDA through local Community Action Agencies.',
 '$300–$1,500 per year toward heating bills',
 'Indiana households with income at or below 60% of State Median Income (~200% FPL)',
 '1-800-622-4973', 'https://www.in.gov/ihcda/2329.htm',
 1300, 'state', 'IN', null, 'indiana-liheap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Indiana Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Hoosiers who lost their job through no fault of their own. Administered by the Indiana Department of Workforce Development. Most claimants receive benefits for up to 26 weeks.',
 'Up to $390/week (~$20,300/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-800-891-6499', 'https://www.in.gov/dwd',
 13000, 'state', 'IN', null, 'indiana-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Indiana Department of Veterans Affairs', 'Veteran Services',
 'The state agency that helps Indiana veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through County Veteran Service Officers and the Indiana Veterans Home.',
 'Free benefits counseling plus access to state veterans home',
 'Indiana veterans, active-duty service members, and their dependents',
 '1-317-232-3910', 'https://www.in.gov/dva',
 5000, 'state', 'IN', null, 'indiana-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Indiana Division of Aging', 'Senior Services',
 'FSSA''s Division of Aging coordinates Indiana''s 16 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Hoosiers 60 and older and their family caregivers',
 '1-888-673-0002', 'https://www.in.gov/fssa/da',
 2000, 'state', 'IN', null, 'indiana-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Indiana 211', 'Information & Referral',
 'Indiana 211 is the statewide health and human services helpline operated by FSSA. Call 2-1-1 or 1-866-211-9966 to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Indiana needing help finding local services',
 '211', 'https://www.in.gov/fssa/indiana-211/',
 0, 'state', 'IN', null, 'indiana-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb);
