-- migration_026: Add Iowa, Kansas, Kentucky, Louisiana, Washington.
--
-- 45 rows. Four expansion-state Medicaids (IA, KY, LA, WA) at 138% FPL with
-- no required_situations. Kansas Medicaid (KanCare) is gated like FL/AL/GA/MS
-- since Kansas did not expand — its important_notes calls out the
-- particularly strict adult-with-kids cutoff (~38% FPL).
--
-- Three LIHEAPs (IA, LA, WA) use 60% State Median Income, which approximates
-- 200% FPL — each carries the same SMI note we wrote in migration_025.
-- Kansas LIEAP and Kentucky LIHEAP follow the federal default (150% FPL)
-- and get no note.

insert into programs (
  name, category, description, potential_benefit, who_qualifies,
  phone_number, apply_url, benefit_value, scope, state, jurisdiction_name,
  slug, is_active, important_notes, eligibility_rules
) values

-- ── IOWA ────────────────────────────────────────────────────────────
('Iowa Medicaid (Iowa Health and Wellness Plan)', 'Health Insurance',
 'Iowa Medicaid, including the Iowa Health and Wellness Plan for adults, provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Iowa expanded Medicaid for adults under the ACA.',
 'Full health coverage at little to no cost',
 'Iowa adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-800-338-8366', 'https://hhsservices.iowa.gov',
 15000, 'state', 'IA', null, 'iowa-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Iowa SNAP', 'Food Assistance',
 'Iowa''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by Iowa HHS through hhsservices.iowa.gov.',
 'Up to ~$975/month for a family of four',
 'Iowa households with gross monthly income at or below 130% of the federal poverty level',
 '1-877-347-5678', 'https://hhsservices.iowa.gov',
 11676, 'state', 'IA', null, 'iowa-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Iowa Family Investment Program (FIP)', 'Cash Assistance',
 'Monthly cash assistance for low-income Iowa families with minor children, plus access to PROMISE JOBS employment and training services. Administered by Iowa HHS.',
 'Up to ~$426/month for a family of three',
 'Iowa families with minor children and limited income/resources',
 '1-877-347-5678', 'https://hhsservices.iowa.gov',
 3500, 'state', 'IA', null, 'iowa-fip', true, null,
 '{"max_monthly_income": 1000, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Iowa Finance Authority', 'Housing Assistance',
 'Iowa Finance Authority administers the state''s first-time and qualifying repeat homebuyer programs (FirstHome, Homes for Iowans), with down-payment assistance and below-market mortgage rates.',
 'Down-payment assistance plus below-market mortgage rates',
 'Iowa homebuyers meeting program income and home-price limits',
 '515-452-0400', 'https://www.iowafinance.com',
 10000, 'state', 'IA', null, 'iowa-finance-authority', true, null,
 '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb),
('Iowa LIHEAP / LIEAP', 'Utility Assistance',
 'Iowa''s federally-funded Low-Income Home Energy Assistance Program helps qualifying households pay heating bills and crisis energy needs. Administered by Iowa HHS through Community Action Agencies.',
 '$300–$1,500 per year toward heating bills',
 'Iowa households with income at or below 60% of State Median Income (~200% FPL)',
 '515-281-0859', 'https://hhs.iowa.gov/programs/welcome-iowa-hhs/community-action-agency-cap-help/liheap',
 1300, 'state', 'IA', null, 'iowa-liheap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Iowa Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Iowans who lost their job through no fault of their own. Administered by Iowa Workforce Development. Most claimants receive benefits for up to 26 weeks.',
 'Up to $725/week (~$37,700/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-866-239-0843', 'https://www.iowaworkforcedevelopment.gov',
 13000, 'state', 'IA', null, 'iowa-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Iowa Department of Veterans Affairs', 'Veteran Services',
 'The state agency that helps Iowa veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through county Commissions of Veteran Affairs and the Iowa Veterans Home.',
 'Free benefits counseling plus access to state veterans home',
 'Iowa veterans, active-duty service members, and their dependents',
 '515-242-5331', 'https://va.iowa.gov',
 5000, 'state', 'IA', null, 'iowa-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Iowa Department on Aging', 'Senior Services',
 'Iowa''s Department on Aging coordinates the state''s 13 Area Agencies on Aging through the LifeLong Links portal, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Iowans 60 and older and their family caregivers',
 '515-725-3333', 'https://iowaaging.gov',
 2000, 'state', 'IA', null, 'iowa-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Iowa 211', 'Information & Referral',
 'Iowa 211 is the statewide health and human services helpline. Call 2-1-1 or visit 211iowa.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Iowa needing help finding local services',
 '211', 'https://211iowa.org',
 0, 'state', 'IA', null, 'iowa-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── KANSAS (non-expansion) ──────────────────────────────────────────
('KanCare (Kansas Medicaid)', 'Health Insurance',
 'KanCare is the state Medicaid program, providing health coverage including doctor visits, hospital care, prescriptions, and preventive services. Kansas did not expand Medicaid; adult eligibility is among the strictest in the nation.',
 'Full health coverage at little to no cost',
 'Low-income parents of minor children, pregnant women, people with disabilities, seniors, and children',
 '1-800-792-4884', 'https://www.kancare.ks.gov',
 15000, 'state', 'KS', null, 'kansas-medicaid', true,
 'Kansas did not expand Medicaid. Adult eligibility is among the strictest in the nation — for parents with children, income limit is approximately 38% of FPL. Adults without children typically don''t qualify regardless of income.',
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": ["single_parent", "pregnant", "disability"]}'::jsonb),
('Kansas SNAP (Food Assistance)', 'Food Assistance',
 'Kansas''s Supplemental Nutrition Assistance Program provides monthly food benefits on a Vision Card. Administered by the Department for Children and Families.',
 'Up to ~$975/month for a family of four',
 'Kansas households with gross monthly income at or below 130% of the federal poverty level',
 '1-888-369-4777', 'https://www.dcf.ks.gov/services/ees/Pages/Food/FoodAssistance.aspx',
 11676, 'state', 'KS', null, 'kansas-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Kansas TANF', 'Cash Assistance',
 'Monthly cash assistance for low-income Kansas families with minor children, plus access to employment services. Administered by the Department for Children and Families.',
 'Up to ~$429/month for a family of three',
 'Kansas families with minor children and limited income/resources',
 '1-888-369-4777', 'https://www.dcf.ks.gov',
 3500, 'state', 'KS', null, 'kansas-tanf', true, null,
 '{"max_monthly_income": 750, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Kansas Housing Resources Corporation (KHRC)', 'Housing Assistance',
 'KHRC administers Kansas''s first-time homebuyer programs, with down-payment assistance and below-market mortgage rates. Income and home-price limits vary by county.',
 'Down-payment assistance plus below-market mortgage rates',
 'Kansas homebuyers meeting KHRC program income and home-price limits',
 '785-217-2000', 'https://kshousingcorp.org',
 10000, 'state', 'KS', null, 'kansas-housing-resources', true, null,
 '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb),
('Kansas LIEAP (Low Income Energy Assistance Program)', 'Utility Assistance',
 'Kansas''s federally-funded Low-Income Energy Assistance Program helps qualifying households pay heating bills and crisis energy needs. Administered by the Department for Children and Families.',
 '$300–$1,500 per year toward heating bills',
 'Kansas households with income at or below 150% of the federal poverty level',
 '1-800-432-0043', 'https://www.dcf.ks.gov/services/ees/Pages/EnergyAssistance.aspx',
 1300, 'state', 'KS', null, 'kansas-lieap', true, null,
 '{"max_income_percent_fpl": 150, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Kansas Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Kansans who lost their job through no fault of their own. Administered by the Kansas Department of Labor. Most claimants receive benefits for up to 16 weeks.',
 'Up to $589/week (~$30,600/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-800-292-6333', 'https://www.dol.ks.gov',
 13000, 'state', 'KS', null, 'kansas-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Kansas Commission on Veterans Affairs Office', 'Veteran Services',
 'The state agency that helps Kansas veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Representatives and the Kansas Soldiers'' Home and Veterans'' Home.',
 'Free benefits counseling plus access to state veterans homes',
 'Kansas veterans, active-duty service members, and their dependents',
 '785-296-3976', 'https://kcva.ks.gov',
 5000, 'state', 'KS', null, 'kansas-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Kansas Department for Aging and Disability Services (KDADS)', 'Senior Services',
 'KDADS administers Kansas''s 11 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Kansans 60 and older and their family caregivers',
 '1-844-431-6622', 'https://kdads.ks.gov',
 2000, 'state', 'KS', null, 'kansas-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Kansas 211', 'Information & Referral',
 'Kansas 211 is the statewide health and human services helpline operated by United Way of the Plains. Call 2-1-1 or visit 211kansas.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential.',
 'Free referral to local assistance programs',
 'Anyone in Kansas needing help finding local services',
 '211', 'https://211kansas.org',
 0, 'state', 'KS', null, 'kansas-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── KENTUCKY ────────────────────────────────────────────────────────
('Kentucky Medicaid', 'Health Insurance',
 'Kentucky Medicaid provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Kentucky expanded Medicaid for adults under the ACA. Apply through kynect.',
 'Full health coverage at little to no cost',
 'Kentucky adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-855-459-6328', 'https://kynect.ky.gov',
 15000, 'state', 'KY', null, 'kentucky-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Kentucky SNAP', 'Food Assistance',
 'Kentucky''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by the Department for Community Based Services through kynect.',
 'Up to ~$975/month for a family of four',
 'Kentucky households with gross monthly income at or below 130% of the federal poverty level',
 '1-855-306-8959', 'https://kynect.ky.gov',
 11676, 'state', 'KY', null, 'kentucky-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Kentucky Transitional Assistance Program (KTAP)', 'Cash Assistance',
 'Monthly cash assistance for low-income Kentucky families with minor children, plus access to employment and training services. Administered by the Department for Community Based Services.',
 'Up to ~$262/month for a family of three',
 'Kentucky families with minor children and very low income',
 '1-855-306-8959', 'https://kynect.ky.gov',
 3500, 'state', 'KY', null, 'kentucky-ktap', true, null,
 '{"max_monthly_income": 700, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Kentucky Housing Corporation (KHC)', 'Housing Assistance',
 'KHC administers Kentucky''s first-time homebuyer programs, with down-payment assistance and below-market mortgage rates. Income and home-price limits vary by county.',
 'Down-payment assistance plus below-market mortgage rates',
 'Kentucky homebuyers meeting KHC program income and home-price limits',
 '1-800-633-8896', 'https://www.kyhousing.org',
 10000, 'state', 'KY', null, 'kentucky-housing-corporation', true, null,
 '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb),
('Kentucky LIHEAP', 'Utility Assistance',
 'Kentucky''s federally-funded LIHEAP helps qualifying households pay heating bills and crisis energy needs. Administered by Community Action Kentucky through 23 local Community Action Agencies.',
 '$300–$1,500 per year toward heating bills',
 'Kentucky households with income at or below 150% of the federal poverty level',
 '1-800-456-3452', 'https://www.cap.ky.gov',
 1300, 'state', 'KY', null, 'kentucky-liheap', true, null,
 '{"max_income_percent_fpl": 150, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Kentucky Office of Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Kentuckians who lost their job through no fault of their own. Administered by the Kentucky Career Center. Most claimants receive benefits for up to 26 weeks.',
 'Up to $665/week (~$34,600/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-502-875-0442', 'https://kcc.ky.gov',
 13000, 'state', 'KY', null, 'kentucky-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Kentucky Department of Veterans Affairs', 'Veteran Services',
 'The state agency that helps Kentucky veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Field Representatives and four Kentucky Veterans Centers.',
 'Free benefits counseling plus access to state veterans centers',
 'Kentucky veterans, active-duty service members, and their dependents',
 '502-564-9203', 'https://veterans.ky.gov',
 5000, 'state', 'KY', null, 'kentucky-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Kentucky Department for Aging and Independent Living (DAIL)', 'Senior Services',
 'DAIL coordinates Kentucky''s 15 Area Agencies on Aging and Independent Living, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Kentuckians 60 and older and their family caregivers',
 '502-564-6930', 'https://www.chfs.ky.gov/agencies/dail',
 2000, 'state', 'KY', null, 'kentucky-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Kentucky 211', 'Information & Referral',
 'Kentucky 211 is the statewide health and human services helpline. Call 2-1-1 or visit kentucky211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Kentucky needing help finding local services',
 '211', 'https://kentucky211.org',
 0, 'state', 'KY', null, 'kentucky-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── LOUISIANA ───────────────────────────────────────────────────────
('Healthy Louisiana (Louisiana Medicaid)', 'Health Insurance',
 'Healthy Louisiana is the state Medicaid program, providing health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Louisiana expanded Medicaid for adults under the ACA.',
 'Full health coverage at little to no cost',
 'Louisiana adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-888-342-6207', 'https://ldh.la.gov/medicaid',
 15000, 'state', 'LA', null, 'louisiana-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Louisiana SNAP', 'Food Assistance',
 'Louisiana''s Supplemental Nutrition Assistance Program provides monthly food benefits on a Louisiana Purchase Card (EBT). Administered by the Department of Children and Family Services.',
 'Up to ~$975/month for a family of four',
 'Louisiana households with gross monthly income at or below 130% of the federal poverty level',
 '1-888-524-3578', 'https://www.dcfs.la.gov/page/snap',
 11676, 'state', 'LA', null, 'louisiana-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Louisiana Family Independence Temporary Assistance Program (FITAP)', 'Cash Assistance',
 'Monthly cash assistance for very low-income Louisiana families with minor children, plus access to employment and training services. Administered by the Department of Children and Family Services.',
 'Up to ~$240/month for a family of three',
 'Louisiana families with minor children and very low income',
 '1-888-524-3578', 'https://www.dcfs.la.gov',
 3500, 'state', 'LA', null, 'louisiana-fitap', true, null,
 '{"max_monthly_income": 600, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Louisiana Housing Corporation (LHC)', 'Housing Assistance',
 'LHC administers Louisiana''s first-time homebuyer programs, with down-payment assistance and below-market mortgage rates. Income and home-price limits vary by parish.',
 'Down-payment assistance plus below-market mortgage rates',
 'Louisiana homebuyers meeting LHC program income and home-price limits',
 '1-225-763-8700', 'https://www.lhc.la.gov',
 10000, 'state', 'LA', null, 'louisiana-housing-corporation', true, null,
 '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb),
('Louisiana LIHEAP / LSEAP', 'Utility Assistance',
 'Louisiana''s federally-funded Low-Income Home Energy Assistance Program helps qualifying households pay cooling and heating bills and crisis energy needs. Administered by the Louisiana Housing Corporation through Community Action Agencies.',
 '$300–$1,500 per year toward energy bills',
 'Louisiana households with income at or below 60% of State Median Income (~200% FPL)',
 '1-225-763-8700', 'https://www.lhc.la.gov/program/low-income-energy-assistance-program-liheap',
 1300, 'state', 'LA', null, 'louisiana-lseap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Louisiana Workforce Commission Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Louisianans who lost their job through no fault of their own. Administered by the Louisiana Workforce Commission. Most claimants receive benefits for up to 26 weeks.',
 'Up to $275/week (~$14,300/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-866-783-5567', 'https://www.laworks.net',
 13000, 'state', 'LA', null, 'louisiana-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Louisiana Department of Veterans Affairs', 'Veteran Services',
 'The state agency that helps Louisiana veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Affairs Officers and five Louisiana Veterans Homes.',
 'Free benefits counseling plus access to state veterans homes',
 'Louisiana veterans, active-duty service members, and their dependents',
 '225-219-5000', 'https://www.vetaffairs.la.gov',
 5000, 'state', 'LA', null, 'louisiana-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Louisiana Governor''s Office of Elderly Affairs (GOEA)', 'Senior Services',
 'GOEA coordinates Louisiana''s Area Agencies on Aging and parish-level Councils on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Louisianans 60 and older and their family caregivers',
 '225-342-7100', 'https://goea.louisiana.gov',
 2000, 'state', 'LA', null, 'louisiana-elderly-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Louisiana 211', 'Information & Referral',
 'Louisiana 211 is the statewide health and human services helpline operated by the Louisiana Association of United Ways. Call 2-1-1 or visit louisiana211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Louisiana needing help finding local services',
 '211', 'https://www.louisiana211.org',
 0, 'state', 'LA', null, 'louisiana-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── WASHINGTON ──────────────────────────────────────────────────────
('Washington Apple Health (Washington Medicaid)', 'Health Insurance',
 'Apple Health is the state Medicaid program, providing health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Washington expanded Medicaid for adults under the ACA. Apply through Washington Healthplanfinder.',
 'Full health coverage at little to no cost',
 'Washington adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-855-923-4633', 'https://www.wahealthplanfinder.org',
 15000, 'state', 'WA', null, 'washington-apple-health', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Washington Basic Food (SNAP)', 'Food Assistance',
 'Washington''s Basic Food program (SNAP) provides monthly food benefits on a Washington Quest Card (EBT). Administered by the Department of Social and Health Services.',
 'Up to ~$975/month for a family of four',
 'Washington households with gross monthly income at or below 130% of the federal poverty level',
 '1-877-501-2233', 'https://www.washingtonconnection.org',
 11676, 'state', 'WA', null, 'washington-basic-food', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Washington WorkFirst (TANF)', 'Cash Assistance',
 'Monthly cash assistance for low-income Washington families with minor children, plus access to employment and training services through WorkFirst. Administered by the Department of Social and Health Services. Washington WorkFirst benefits are among the more generous in the nation.',
 'Up to ~$654/month for a family of three',
 'Washington families with minor children and limited income/resources',
 '1-877-501-2233', 'https://www.washingtonconnection.org',
 3500, 'state', 'WA', null, 'washington-workfirst', true, null,
 '{"max_monthly_income": 1400, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Washington State Housing Finance Commission (WSHFC)', 'Housing Assistance',
 'WSHFC administers Washington''s first-time homebuyer programs (Home Advantage, House Key Opportunity), with down-payment assistance and below-market mortgage rates. Income and home-price limits vary by county.',
 'Down-payment assistance plus below-market mortgage rates',
 'Washington homebuyers meeting WSHFC program income and home-price limits',
 '1-800-767-4663', 'https://www.wshfc.org',
 10000, 'state', 'WA', null, 'washington-housing-finance', true, null,
 '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb),
('Washington LIHEAP', 'Utility Assistance',
 'Washington''s federally-funded LIHEAP helps qualifying households pay heating bills and crisis energy needs. Administered by the Department of Commerce through local Community Action Agencies.',
 '$300–$1,500 per year toward heating bills',
 'Washington households with income at or below 60% of State Median Income (~200% FPL)',
 '1-877-501-2233', 'https://www.commerce.wa.gov/serving-communities/low-income-home-energy-assistance-program-liheap/',
 1300, 'state', 'WA', null, 'washington-liheap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Washington Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Washingtonians who lost their job through no fault of their own. Administered by the Employment Security Department. Most claimants receive benefits for up to 26 weeks.',
 'Up to $1,079/week (~$56,100/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-800-318-6022', 'https://esd.wa.gov',
 13000, 'state', 'WA', null, 'washington-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Washington Department of Veterans Affairs (WDVA)', 'Veteran Services',
 'The state agency that helps Washington veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and four Washington State Veterans Homes.',
 'Free benefits counseling plus access to state veterans homes and emergency funds',
 'Washington veterans, active-duty service members, and their dependents',
 '1-800-562-2308', 'https://www.dva.wa.gov',
 5000, 'state', 'WA', null, 'washington-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Washington Aging and Long-Term Support Administration (ALTSA)', 'Senior Services',
 'ALTSA coordinates Washington''s 13 Area Agencies on Aging and the statewide Family Caregiver Support Program, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Washingtonians 60 and older and their family caregivers',
 '1-800-422-3263', 'https://www.dshs.wa.gov/altsa',
 2000, 'state', 'WA', null, 'washington-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Washington 211', 'Information & Referral',
 'Washington 211 is the statewide health and human services helpline. Call 2-1-1 or visit wa211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Washington needing help finding local services',
 '211', 'https://wa211.org',
 0, 'state', 'WA', null, 'washington-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb);
