-- migration_027: Add Montana, Nebraska, Ohio, Oklahoma, Tennessee.
--
-- 40 rows — 8 categories per state (Medicaid, SNAP, TANF, LIHEAP,
-- unemployment, veterans, aging, 211). The state housing finance slot
-- is deliberately omitted; migration_028 deactivated those programs from
-- earlier batches as wealth-building rows that don't fit MyPublicAid's
-- consumption-support focus. The rental-assistance pass is a separate
-- research project (see TODO.md).
--
-- Four expansion-state Medicaids (MT, NE, OH, OK) at 138% FPL with no
-- required_situations. Tennessee is non-expansion — TennCare is gated
-- by ["single_parent","pregnant","disability"] like FL/AL/GA/MS/KS.
--
-- Ohio HEAP uses 175% FPL — Ohio's actual eligibility threshold, more
-- generous than federal 150%. Montana and Oklahoma LIEAPs use 60% SMI,
-- modeled as 200% FPL with the standard SMI note.

insert into programs (
  name, category, description, potential_benefit, who_qualifies,
  phone_number, apply_url, benefit_value, scope, state, jurisdiction_name,
  slug, is_active, important_notes, eligibility_rules
) values

-- ── MONTANA ─────────────────────────────────────────────────────────
('Montana Medicaid', 'Health Insurance',
 'Montana Medicaid provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Montana expanded Medicaid for adults under the ACA via the HELP Act.',
 'Full health coverage at little to no cost',
 'Montana adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-800-362-8312', 'https://dphhs.mt.gov/MontanaHealthcarePrograms',
 15000, 'state', 'MT', null, 'montana-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Montana SNAP', 'Food Assistance',
 'Montana''s Supplemental Nutrition Assistance Program provides monthly food benefits on a Montana Access EBT card. Administered by DPHHS.',
 'Up to ~$975/month for a family of four',
 'Montana households with gross monthly income at or below 130% of the federal poverty level',
 '1-888-706-1535', 'https://dphhs.mt.gov/hcsd/snap',
 11676, 'state', 'MT', null, 'montana-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Montana FAIM (Families Achieving Independence in Montana)', 'Cash Assistance',
 'Monthly cash assistance for low-income Montana families with minor children, plus access to employment and training services. Administered by DPHHS.',
 'Up to ~$588/month for a family of three',
 'Montana families with minor children and limited income/resources',
 '1-888-706-1535', 'https://dphhs.mt.gov/hcsd/tanf',
 3500, 'state', 'MT', null, 'montana-faim', true, null,
 '{"max_monthly_income": 1000, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Montana LIEAP', 'Utility Assistance',
 'Montana''s federally-funded Low-Income Energy Assistance Program helps qualifying households pay heating bills and crisis energy needs. Administered by DPHHS through Human Resource Development Councils.',
 '$300–$1,500 per year toward heating bills',
 'Montana households with income at or below 60% of State Median Income (~200% FPL)',
 '1-833-317-1080', 'https://dphhs.mt.gov/hcsd/energyassistance',
 1300, 'state', 'MT', null, 'montana-lieap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Montana Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Montanans who lost their job through no fault of their own. Administered by the Montana Department of Labor and Industry. Most claimants receive benefits for up to 28 weeks.',
 'Up to $629/week (~$32,700/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-406-444-2545', 'https://uid.dli.mt.gov',
 13000, 'state', 'MT', null, 'montana-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Montana Veterans Affairs Division', 'Veteran Services',
 'The state agency that helps Montana veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through Veterans Service Officers and the Montana Veterans Home.',
 'Free benefits counseling plus access to state veterans home',
 'Montana veterans, active-duty service members, and their dependents',
 '406-324-3742', 'https://dma.mt.gov/MVAD',
 5000, 'state', 'MT', null, 'montana-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Montana Senior and Long Term Care', 'Senior Services',
 'Montana DPHHS''s Senior and Long Term Care Division coordinates the state''s 10 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Montanans 60 and older and their family caregivers',
 '1-800-551-3191', 'https://dphhs.mt.gov/sltc',
 2000, 'state', 'MT', null, 'montana-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Montana 211', 'Information & Referral',
 'Montana 211 is the statewide health and human services helpline. Call 2-1-1 or visit montana211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Montana needing help finding local services',
 '211', 'https://montana211.org',
 0, 'state', 'MT', null, 'montana-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── NEBRASKA ────────────────────────────────────────────────────────
('Heritage Health (Nebraska Medicaid)', 'Health Insurance',
 'Heritage Health is Nebraska''s Medicaid program, providing health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Nebraska expanded Medicaid for adults in 2020 under the ACA. Apply through ACCESSNebraska.',
 'Full health coverage at little to no cost',
 'Nebraska adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-855-632-7633', 'https://accessnebraska.ne.gov',
 15000, 'state', 'NE', null, 'nebraska-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Nebraska SNAP', 'Food Assistance',
 'Nebraska''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by the Department of Health and Human Services through ACCESSNebraska.',
 'Up to ~$975/month for a family of four',
 'Nebraska households with gross monthly income at or below 130% of the federal poverty level',
 '1-800-383-4278', 'https://accessnebraska.ne.gov',
 11676, 'state', 'NE', null, 'nebraska-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Nebraska Aid to Dependent Children (ADC)', 'Cash Assistance',
 'Monthly cash assistance for low-income Nebraska families with minor children, plus access to employment and training services. Administered by the Department of Health and Human Services.',
 'Up to ~$485/month for a family of three',
 'Nebraska families with minor children and limited income/resources',
 '1-800-383-4278', 'https://accessnebraska.ne.gov',
 3500, 'state', 'NE', null, 'nebraska-adc', true, null,
 '{"max_monthly_income": 900, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Nebraska LIHEAP', 'Utility Assistance',
 'Nebraska''s federally-funded LIHEAP helps qualifying households pay heating bills and crisis energy needs. Administered by the Department of Health and Human Services.',
 '$300–$1,500 per year toward heating bills',
 'Nebraska households with income at or below 150% of the federal poverty level',
 '1-800-383-4278', 'https://dhhs.ne.gov/Pages/Energy-Assistance.aspx',
 1300, 'state', 'NE', null, 'nebraska-liheap', true, null,
 '{"max_income_percent_fpl": 150, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Nebraska Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Nebraskans who lost their job through no fault of their own. Administered by the Nebraska Department of Labor. Most claimants receive benefits for up to 26 weeks.',
 'Up to $514/week (~$26,700/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '402-458-2500', 'https://dol.nebraska.gov',
 13000, 'state', 'NE', null, 'nebraska-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Nebraska Department of Veterans'' Affairs', 'Veteran Services',
 'The state agency that helps Nebraska veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through County Veteran Service Officers and four state veterans homes.',
 'Free benefits counseling plus access to state veterans homes',
 'Nebraska veterans, active-duty service members, and their dependents',
 '402-471-2458', 'https://veterans.nebraska.gov',
 5000, 'state', 'NE', null, 'nebraska-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Nebraska State Unit on Aging', 'Senior Services',
 'Nebraska DHHS''s State Unit on Aging coordinates the state''s 8 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Nebraskans 60 and older and their family caregivers',
 '1-877-797-7227', 'https://dhhs.ne.gov/Pages/Aging-and-Disability.aspx',
 2000, 'state', 'NE', null, 'nebraska-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Nebraska 211', 'Information & Referral',
 'Nebraska 211 is the statewide health and human services helpline operated by United Way of the Midlands. Call 2-1-1 or visit ne211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Nebraska needing help finding local services',
 '211', 'https://search.ne211.org',
 0, 'state', 'NE', null, 'nebraska-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── OHIO ────────────────────────────────────────────────────────────
('Ohio Medicaid', 'Health Insurance',
 'Ohio Medicaid provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Ohio expanded Medicaid for adults under the ACA. Apply through Ohio Benefits.',
 'Full health coverage at little to no cost',
 'Ohio adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-800-324-8680', 'https://ohiobenefits.gov',
 15000, 'state', 'OH', null, 'ohio-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Ohio SNAP (Food Assistance)', 'Food Assistance',
 'Ohio''s Supplemental Nutrition Assistance Program provides monthly food benefits on an Ohio Direction Card. Administered by the Department of Job and Family Services through Ohio Benefits.',
 'Up to ~$975/month for a family of four',
 'Ohio households with gross monthly income at or below 130% of the federal poverty level',
 '1-866-244-0071', 'https://ohiobenefits.gov',
 11676, 'state', 'OH', null, 'ohio-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Ohio Works First (TANF)', 'Cash Assistance',
 'Monthly cash assistance for low-income Ohio families with minor children, plus access to employment and training services. Administered by the Department of Job and Family Services.',
 'Up to ~$571/month for a family of three',
 'Ohio families with minor children and limited income/resources',
 '1-866-244-0071', 'https://ohiobenefits.gov',
 3500, 'state', 'OH', null, 'ohio-works-first', true, null,
 '{"max_monthly_income": 1200, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Ohio HEAP (Home Energy Assistance Program)', 'Utility Assistance',
 'Ohio''s federally-funded HEAP helps qualifying households pay heating, cooling, and crisis energy bills. Administered by the Ohio Development Services Agency. Ohio''s eligibility threshold (175% FPL) is more generous than the federal default of 150% FPL.',
 '$300–$1,500 per year toward energy bills',
 'Ohio households with income at or below 175% of the federal poverty level',
 '1-800-282-0880', 'https://energyhelp.ohio.gov',
 1300, 'state', 'OH', null, 'ohio-heap', true, null,
 '{"max_income_percent_fpl": 175, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Ohio Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Ohioans who lost their job through no fault of their own. Administered by the Ohio Department of Job and Family Services. Most claimants receive benefits for up to 26 weeks.',
 'Up to $654/week (~$34,000/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-877-644-6562', 'https://jfs.ohio.gov/ouio',
 13000, 'state', 'OH', null, 'ohio-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Ohio Department of Veterans Services', 'Veteran Services',
 'The state agency that helps Ohio veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through County Veterans Service Commissions and the Ohio Veterans Homes.',
 'Free benefits counseling plus access to state veterans homes',
 'Ohio veterans, active-duty service members, and their dependents',
 '1-877-644-6838', 'https://dvs.ohio.gov',
 5000, 'state', 'OH', null, 'ohio-veterans-services', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Ohio Department of Aging', 'Senior Services',
 'Ohio''s Department of Aging coordinates the state''s 12 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Ohioans 60 and older and their family caregivers',
 '1-800-266-4346', 'https://aging.ohio.gov',
 2000, 'state', 'OH', null, 'ohio-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Ohio 211', 'Information & Referral',
 'Ohio 211 is the statewide health and human services helpline operated by 13 regional United Way 211 centers. Call 2-1-1 or visit ohio211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Ohio needing help finding local services',
 '211', 'https://ohio211.org',
 0, 'state', 'OH', null, 'ohio-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── OKLAHOMA ────────────────────────────────────────────────────────
('SoonerCare (Oklahoma Medicaid)', 'Health Insurance',
 'SoonerCare is Oklahoma''s Medicaid program, providing health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Oklahoma expanded Medicaid for adults in 2021 under the ACA.',
 'Full health coverage at little to no cost',
 'Oklahoma adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-800-987-7767', 'https://mysoonercare.org',
 15000, 'state', 'OK', null, 'oklahoma-soonercare', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Oklahoma SNAP', 'Food Assistance',
 'Oklahoma''s Supplemental Nutrition Assistance Program provides monthly food benefits on an Access Oklahoma EBT card. Administered by the Oklahoma Department of Human Services.',
 'Up to ~$975/month for a family of four',
 'Oklahoma households with gross monthly income at or below 130% of the federal poverty level',
 '1-405-521-3646', 'https://okdhslive.org',
 11676, 'state', 'OK', null, 'oklahoma-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Oklahoma TANF', 'Cash Assistance',
 'Monthly cash assistance for low-income Oklahoma families with minor children, plus access to employment and training services. Administered by the Oklahoma Department of Human Services.',
 'Up to ~$292/month for a family of three',
 'Oklahoma families with minor children and very low income',
 '1-405-521-3646', 'https://okdhslive.org',
 3500, 'state', 'OK', null, 'oklahoma-tanf', true, null,
 '{"max_monthly_income": 700, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Oklahoma LIHEAP', 'Utility Assistance',
 'Oklahoma''s federally-funded LIHEAP helps qualifying households pay heating, cooling, and crisis energy bills. Administered by the Oklahoma Department of Human Services.',
 '$300–$1,500 per year toward energy bills',
 'Oklahoma households with income at or below 60% of State Median Income (~200% FPL)',
 '1-866-411-1877', 'https://oklahoma.gov/okdhs/services/leap',
 1300, 'state', 'OK', null, 'oklahoma-liheap', true,
 'Eligibility uses 60% State Median Income, which approximates 200% FPL in this state. The state agency may reference SMI rather than FPL when you call.',
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Oklahoma Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Oklahomans who lost their job through no fault of their own. Administered by the Oklahoma Employment Security Commission. Most claimants receive benefits for up to 26 weeks.',
 'Up to $539/week (~$28,000/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-800-555-1554', 'https://oklahoma.gov/oesc',
 13000, 'state', 'OK', null, 'oklahoma-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Oklahoma Department of Veterans Affairs', 'Veteran Services',
 'The state agency that helps Oklahoma veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through County Veterans Service Officers and seven Oklahoma Veterans Centers.',
 'Free benefits counseling plus access to state veterans centers',
 'Oklahoma veterans, active-duty service members, and their dependents',
 '1-888-655-2838', 'https://oklahoma.gov/odva',
 5000, 'state', 'OK', null, 'oklahoma-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Oklahoma DHS Aging Services', 'Senior Services',
 'OKDHS Aging Services Division coordinates Oklahoma''s 11 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Oklahomans 60 and older and their family caregivers',
 '1-800-211-2116', 'https://oklahoma.gov/okdhs/services/asd',
 2000, 'state', 'OK', null, 'oklahoma-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Oklahoma 211', 'Information & Referral',
 'Oklahoma 211 is the statewide health and human services helpline operated by Heartline (western Oklahoma) and Tulsa Area United Way (eastern Oklahoma). Call 2-1-1 or visit 211oklahoma.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Oklahoma needing help finding local services',
 '211', 'https://211oklahoma.org',
 0, 'state', 'OK', null, 'oklahoma-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── TENNESSEE (non-expansion) ───────────────────────────────────────
('TennCare (Tennessee Medicaid)', 'Health Insurance',
 'TennCare is the state Medicaid program, providing health coverage including doctor visits, hospital care, prescriptions, and preventive services. Tennessee did not expand Medicaid for non-disabled adults, so most adult coverage is limited to parents of minor children, pregnant women, and people with disabilities.',
 'Full health coverage at little to no cost',
 'Low-income parents of minor children, pregnant women, people with disabilities, seniors, and children',
 '1-855-259-0701', 'https://www.tn.gov/tenncare',
 15000, 'state', 'TN', null, 'tennessee-medicaid', true,
 'Tennessee did not expand Medicaid. Most adults without children, disability, or pregnancy do not qualify regardless of income.',
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": ["single_parent", "pregnant", "disability"]}'::jsonb),
('Tennessee SNAP', 'Food Assistance',
 'Tennessee''s Supplemental Nutrition Assistance Program provides monthly food benefits on a Tennessee EBT card. Administered by the Department of Human Services.',
 'Up to ~$975/month for a family of four',
 'Tennessee households with gross monthly income at or below 130% of the federal poverty level',
 '1-866-311-4287', 'https://www.tn.gov/humanservices',
 11676, 'state', 'TN', null, 'tennessee-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Tennessee Families First (TANF)', 'Cash Assistance',
 'Monthly cash assistance for low-income Tennessee families with minor children, plus access to employment and training services. Administered by the Department of Human Services.',
 'Up to ~$387/month for a family of three',
 'Tennessee families with minor children and very low income',
 '1-866-311-4287', 'https://www.tn.gov/humanservices',
 3500, 'state', 'TN', null, 'tennessee-families-first', true, null,
 '{"max_monthly_income": 800, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Tennessee LIHEAP', 'Utility Assistance',
 'Tennessee''s federally-funded LIHEAP helps qualifying households pay heating, cooling, and crisis energy bills. Administered by the Department of Human Services through Community Action Agencies.',
 '$300–$1,500 per year toward energy bills',
 'Tennessee households with income at or below 150% of the federal poverty level',
 '1-866-311-4287', 'https://www.tn.gov/humanservices/for-families/low-income-home-energy-assistance-program-liheap.html',
 1300, 'state', 'TN', null, 'tennessee-liheap', true, null,
 '{"max_income_percent_fpl": 150, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Tennessee Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Tennesseans who lost their job through no fault of their own. Administered by the Tennessee Department of Labor and Workforce Development. Most claimants receive benefits for up to 26 weeks.',
 'Up to $275/week (~$14,300/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-877-813-0950', 'https://www.tn.gov/workforce',
 13000, 'state', 'TN', null, 'tennessee-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Tennessee Department of Veterans Services', 'Veteran Services',
 'The state agency that helps Tennessee veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through County Veterans Service Officers and four Tennessee State Veterans Homes.',
 'Free benefits counseling plus access to state veterans homes',
 'Tennessee veterans, active-duty service members, and their dependents',
 '615-741-2931', 'https://www.tn.gov/veteran',
 5000, 'state', 'TN', null, 'tennessee-veterans-services', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Tennessee Commission on Aging and Disability', 'Senior Services',
 'TCAD coordinates Tennessee''s 9 Area Agencies on Aging and Disability, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Tennesseans 60 and older and their family caregivers',
 '1-866-836-6678', 'https://www.tn.gov/aging',
 2000, 'state', 'TN', null, 'tennessee-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Tennessee 211', 'Information & Referral',
 'Tennessee 211 is the statewide health and human services helpline operated by United Ways of Tennessee. Call 2-1-1 or visit uwtn.org/tn-211 to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Tennessee needing help finding local services',
 '211', 'https://www.uwtn.org/tn-211',
 0, 'state', 'TN', null, 'tennessee-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb);
