-- migration_024: Add Illinois, Arkansas, Georgia, Michigan, Mississippi.
--
-- 45 rows (9 per state) following the migration_022/023 conventions.
-- Three expansion-state Medicaids (IL, AR, MI): 138% FPL, no required_situations.
-- Two non-expansion-state Medicaids (GA, MS): 138% FPL gated by
--   ["single_parent","pregnant","disability"], same shape as FL/AL.
-- Georgia Medicaid carries a longer important_notes mentioning the
-- Pathways to Coverage program for working adults 19-64 with 80+
-- hrs/mo of work/study/community service — the quiz can't capture
-- the work-hours requirement, so the note steers eligible workers
-- to call DCH directly.
-- Illinois LIHEAP uses 200% FPL (IL's actual cap, more generous than
-- the federal 150% default).

insert into programs (
  name, category, description, potential_benefit, who_qualifies,
  phone_number, apply_url, benefit_value, scope, state, jurisdiction_name,
  slug, is_active, important_notes, eligibility_rules
) values

-- ── ILLINOIS (9) ──────────────────────────────────────────────────────
('Illinois Medicaid', 'Health Insurance',
 'Illinois Medicaid provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Illinois expanded Medicaid for adults under the ACA. Apply through ABE (Application for Benefits Eligibility).',
 'Full health coverage at little to no cost',
 'Illinois adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-800-843-6154', 'https://abe.illinois.gov',
 15000, 'state', 'IL', null, 'illinois-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Illinois SNAP', 'Food Assistance',
 'Illinois''s Supplemental Nutrition Assistance Program provides monthly food benefits on a Link card. Administered by the Department of Human Services through ABE.',
 'Up to ~$975/month for a family of four',
 'Illinois households with gross monthly income at or below 130% of the federal poverty level',
 '1-800-843-6154', 'https://abe.illinois.gov',
 11676, 'state', 'IL', null, 'illinois-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Illinois TANF', 'Cash Assistance',
 'Monthly cash assistance for low-income Illinois families with minor children, plus access to employment and training services. Administered by the Department of Human Services.',
 'Up to ~$571/month for a family of three',
 'Illinois families with minor children and limited income/resources',
 '1-800-843-6154', 'https://abe.illinois.gov',
 3500, 'state', 'IL', null, 'illinois-tanf', true, null,
 '{"max_monthly_income": 1100, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Illinois Housing Development Authority (IHDA)', 'Housing Assistance',
 'IHDA administers the state''s first-time homebuyer programs (IHDAccess Mortgage and Smart Buy), with down-payment assistance and below-market mortgage rates. Income and home-price limits vary by county.',
 'Down-payment assistance plus below-market mortgage rates',
 'Illinois homebuyers meeting IHDA program income and home-price limits',
 '312-836-5200', 'https://www.ihda.org',
 10000, 'state', 'IL', null, 'illinois-ihda', true, null,
 '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb),
('Illinois LIHEAP', 'Utility Assistance',
 'Illinois''s federally-funded Low-Income Home Energy Assistance Program helps qualifying households pay heating, cooling, and crisis energy bills. Administered by DCEO through local Community Action Agencies. Illinois''s eligibility threshold (200% FPL) is more generous than most states.',
 '$300–$2,000 per year toward energy bills',
 'Illinois households with income at or below 200% of the federal poverty level',
 '1-877-411-9276', 'https://dceo.illinois.gov/communityservices/homeenergyassistance.html',
 1300, 'state', 'IL', null, 'illinois-liheap', true, null,
 '{"max_income_percent_fpl": 200, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Illinois Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Illinoisans who lost their job through no fault of their own. Administered by the Illinois Department of Employment Security (IDES). Most claimants receive benefits for up to 26 weeks.',
 'Up to $578/week (~$30,000/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-800-244-5631', 'https://ides.illinois.gov',
 13000, 'state', 'IL', null, 'illinois-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Illinois Department of Veterans'' Affairs', 'Veteran Services',
 'The state agency that helps Illinois veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through veterans service officers and four state veterans homes.',
 'Free benefits counseling plus access to state veterans homes and emergency funds',
 'Illinois veterans, active-duty service members, and their dependents',
 '1-833-857-7438', 'https://veterans.illinois.gov',
 5000, 'state', 'IL', null, 'illinois-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Illinois Department on Aging', 'Senior Services',
 'IDoA''s Senior Helpline connects callers to the network of Area Agencies on Aging and Aging and Disability Resource Centers across Illinois — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Illinoisans 60 and older and their family caregivers',
 '1-800-252-8966', 'https://ilaging.illinois.gov',
 2000, 'state', 'IL', null, 'illinois-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Illinois 211', 'Information & Referral',
 'Illinois 211 is the statewide health and human services helpline. Call 2-1-1 or visit 211illinois.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Illinois needing help finding local services',
 '211', 'https://211illinois.org',
 0, 'state', 'IL', null, 'illinois-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── ARKANSAS (9) ──────────────────────────────────────────────────────
('Arkansas Medicaid (ARHOME)', 'Health Insurance',
 'Arkansas Medicaid (Arkansas Health and Opportunity for Me — ARHOME) provides health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Arkansas expanded Medicaid for adults under the ACA.',
 'Full health coverage at little to no cost',
 'Arkansas adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-800-482-8988', 'https://access.arkansas.gov',
 15000, 'state', 'AR', null, 'arkansas-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Arkansas SNAP', 'Food Assistance',
 'Arkansas''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by the Department of Human Services through Access Arkansas.',
 'Up to ~$975/month for a family of four',
 'Arkansas households with gross monthly income at or below 130% of the federal poverty level',
 '1-800-482-8988', 'https://access.arkansas.gov',
 11676, 'state', 'AR', null, 'arkansas-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Arkansas Transitional Employment Assistance (TEA)', 'Cash Assistance',
 'Monthly cash assistance for low-income Arkansas families with minor children, plus job placement services. Administered by the Department of Human Services. Arkansas TEA benefits are among the lowest in the nation.',
 'Up to ~$204/month for a family of three',
 'Arkansas families with minor children and very low income',
 '1-800-482-8988', 'https://access.arkansas.gov',
 3500, 'state', 'AR', null, 'arkansas-tea', true, null,
 '{"max_monthly_income": 700, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Arkansas Development Finance Authority (ADFA)', 'Housing Assistance',
 'ADFA''s Move-Up program offers low-interest mortgages and down-payment assistance to first-time and qualifying repeat buyers. Income and home-price limits vary by county.',
 'Down-payment assistance plus below-market mortgage rates',
 'Arkansas homebuyers meeting ADFA program income and home-price limits',
 '1-800-622-2278', 'https://www.adfa.arkansas.gov',
 10000, 'state', 'AR', null, 'arkansas-adfa', true, null,
 '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb),
('Arkansas LIHEAP', 'Utility Assistance',
 'Arkansas''s federally-funded Low-Income Home Energy Assistance Program helps qualifying households pay heating, cooling, and crisis energy bills. Administered by the Department of Human Services through local Community Action Agencies.',
 '$300–$1,500 per year toward energy bills',
 'Arkansas households with income at or below 150% of the federal poverty level',
 '1-800-482-8988', 'https://humanservices.arkansas.gov/divisions-shared-services/community-service-block-grant/liheap/',
 1300, 'state', 'AR', null, 'arkansas-liheap', true,
 'LIHEAP funds are distributed through local Community Action Agencies — call 211 to find your local provider.',
 '{"max_income_percent_fpl": 150, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Arkansas Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Arkansans who lost their job through no fault of their own. Administered by the Division of Workforce Services. Most claimants receive benefits for up to 16 weeks.',
 'Up to $451/week (~$23,500/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-855-225-4440', 'https://www.dws.arkansas.gov',
 13000, 'state', 'AR', null, 'arkansas-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Arkansas Department of Veterans Affairs', 'Veteran Services',
 'The state agency that helps Arkansas veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through county Veteran Service Officers and three state veterans homes.',
 'Free benefits counseling plus access to state veterans homes',
 'Arkansas veterans, active-duty service members, and their dependents',
 '501-683-2382', 'https://veterans.arkansas.gov',
 5000, 'state', 'AR', null, 'arkansas-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Arkansas Aging, Adult, and Behavioral Health Services', 'Senior Services',
 'DAABHS administers Arkansas''s Aging and Disability Resource Centers, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Arkansans 60 and older and their family caregivers',
 '1-501-682-2441', 'https://humanservices.arkansas.gov/divisions-shared-services/aging-adult-behavioral-health-services/',
 2000, 'state', 'AR', null, 'arkansas-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Arkansas 211', 'Information & Referral',
 'Arkansas 211 is the statewide health and human services helpline. Call 2-1-1 or visit arkansas211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Arkansas needing help finding local services',
 '211', 'https://arkansas211.org',
 0, 'state', 'AR', null, 'arkansas-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── GEORGIA (9) ───────────────────────────────────────────────────────
('Georgia Medicaid', 'Health Insurance',
 'Georgia Medicaid provides health coverage including doctor visits, hospital care, prescriptions, and preventive services. Georgia did not fully expand Medicaid; coverage is generally limited to single parents, pregnant individuals, people with disabilities, seniors, and children. Working adults age 19-64 may qualify for Georgia Pathways to Coverage if they meet a work, study, or community-service requirement.',
 'Full health coverage at little to no cost',
 'Low-income parents of minor children, pregnant women, people with disabilities, seniors, children — plus working adults via Pathways to Coverage',
 '1-866-211-0950', 'https://gateway.ga.gov',
 15000, 'state', 'GA', null, 'georgia-medicaid', true,
 'Georgia did not fully expand Medicaid. If you''re a working adult age 19-64 working/studying/volunteering 80+ hours per month, you may qualify for Georgia Pathways to Coverage (call 1-866-211-0950 to ask). Otherwise, Medicaid is limited to single parents, pregnant individuals, and people with disabilities.',
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": ["single_parent", "pregnant", "disability"]}'::jsonb),
('Georgia SNAP (Food Stamps)', 'Food Assistance',
 'Georgia''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by the Division of Family and Children Services through Georgia Gateway.',
 'Up to ~$975/month for a family of four',
 'Georgia households with gross monthly income at or below 130% of the federal poverty level',
 '1-877-423-4746', 'https://gateway.ga.gov',
 11676, 'state', 'GA', null, 'georgia-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Georgia TANF', 'Cash Assistance',
 'Monthly cash assistance for low-income Georgia families with minor children, plus job placement services. Administered by the Division of Family and Children Services. Georgia TANF benefits are among the lowest in the nation.',
 'Up to ~$280/month for a family of three',
 'Georgia families with minor children and very low income',
 '1-877-423-4746', 'https://gateway.ga.gov',
 3500, 'state', 'GA', null, 'georgia-tanf', true, null,
 '{"max_monthly_income": 700, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Georgia Dream Homeownership Program', 'Housing Assistance',
 'Georgia Dream offers low-interest mortgages and down-payment assistance up to $7,500 for first-time homebuyers, with additional assistance for protectors (teachers, healthcare workers, public safety) and people with disabilities. Income and home-price limits vary by county.',
 'Down-payment assistance plus below-market mortgage rates',
 'First-time homebuyers in Georgia meeting program income and home-price limits',
 '1-800-359-4663', 'https://www.dca.ga.gov',
 10000, 'state', 'GA', null, 'georgia-dream', true, null,
 '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb),
('Georgia LIHEAP / Energy Assistance', 'Utility Assistance',
 'Georgia''s federally-funded Low-Income Home Energy Assistance Program helps qualifying households pay heating, cooling, and crisis energy bills. Administered by the Department of Community Affairs through local Community Action Agencies.',
 '$300–$1,500 per year toward energy bills',
 'Georgia households with income at or below 150% of the federal poverty level',
 '404-679-4940', 'https://www.dca.ga.gov',
 1300, 'state', 'GA', null, 'georgia-liheap', true,
 'LIHEAP funds are distributed through local Community Action Agencies — call 211 to find your local provider.',
 '{"max_income_percent_fpl": 150, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Georgia Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Georgians who lost their job through no fault of their own. Administered by the Georgia Department of Labor. Most claimants receive benefits for up to 14 weeks.',
 'Up to $365/week (~$19,000/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '404-232-3001', 'https://dol.georgia.gov',
 13000, 'state', 'GA', null, 'georgia-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Georgia Department of Veterans Service', 'Veteran Services',
 'The state agency that helps Georgia veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through field offices across the state and two state veterans homes.',
 'Free benefits counseling plus access to state veterans homes',
 'Georgia veterans, active-duty service members, and their dependents',
 '404-656-2300', 'https://veterans.georgia.gov',
 5000, 'state', 'GA', null, 'georgia-veterans-service', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Georgia Division of Aging Services (GA Cares)', 'Senior Services',
 'GA Cares is Georgia''s Aging and Disability Resource Connection, the statewide entry point for seniors and family caregivers seeking local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Georgians 60 and older and their family caregivers',
 '1-866-552-4464', 'https://aging.georgia.gov',
 2000, 'state', 'GA', null, 'georgia-aging', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Georgia 211', 'Information & Referral',
 'Georgia 211 is the statewide health and human services helpline operated by the United Ways of Georgia. Call 2-1-1 or visit unitedwayga.org/ga211 to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Georgia needing help finding local services',
 '211', 'https://unitedwayga.org/ga211/',
 0, 'state', 'GA', null, 'georgia-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── MICHIGAN (9) ──────────────────────────────────────────────────────
('Michigan Medicaid (Healthy Michigan Plan)', 'Health Insurance',
 'Healthy Michigan Plan is the state Medicaid program, providing health coverage including doctor visits, hospital care, prescriptions, mental health, and preventive services. Michigan expanded Medicaid for adults under the ACA. Apply through MI Bridges.',
 'Full health coverage at little to no cost',
 'Michigan adults at or below 138% of the federal poverty level, plus children, pregnant women, seniors, and people with disabilities at higher limits',
 '1-800-642-3195', 'https://newmibridges.michigan.gov',
 15000, 'state', 'MI', null, 'michigan-medicaid', true, null,
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Michigan Food Assistance Program (FAP)', 'Food Assistance',
 'Michigan''s SNAP equivalent provides monthly food benefits on a Bridge card. Administered by the Department of Health and Human Services through MI Bridges.',
 'Up to ~$975/month for a family of four',
 'Michigan households with gross monthly income at or below 130% of the federal poverty level',
 '1-800-642-3195', 'https://newmibridges.michigan.gov',
 11676, 'state', 'MI', null, 'michigan-fap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Michigan Family Independence Program (FIP)', 'Cash Assistance',
 'Monthly cash assistance for low-income Michigan families with minor children, plus access to employment and training services. Administered by the Department of Health and Human Services.',
 'Up to ~$492/month for a family of three',
 'Michigan families with minor children and limited income/resources',
 '1-800-642-3195', 'https://newmibridges.michigan.gov',
 3500, 'state', 'MI', null, 'michigan-fip', true, null,
 '{"max_monthly_income": 1100, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Michigan State Housing Development Authority (MSHDA)', 'Housing Assistance',
 'MSHDA administers Michigan''s first-time homebuyer programs (MI Home Loan, MI 10K DPA), with down-payment assistance up to $10,000 and below-market mortgage rates. Income and home-price limits vary by county.',
 'Up to $10,000 in down-payment assistance plus below-market mortgage rates',
 'Michigan homebuyers meeting MSHDA program income and home-price limits',
 '517-373-8370', 'https://www.michigan.gov/mshda',
 10000, 'state', 'MI', null, 'michigan-mshda', true, null,
 '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb),
('Michigan Home Heating Assistance', 'Utility Assistance',
 'Michigan''s federally-funded LIHEAP, including the State Emergency Relief (SER) Energy Services and Home Heating Credit. Administered by the Department of Health and Human Services.',
 '$300–$1,500 per year toward energy bills',
 'Michigan households with income at or below 150% of the federal poverty level',
 '1-855-275-6424', 'https://www.michigan.gov/mdhhs/assistance-programs/cdc/heap',
 1300, 'state', 'MI', null, 'michigan-liheap', true, null,
 '{"max_income_percent_fpl": 150, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Michigan Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Michiganders who lost their job through no fault of their own. Administered by the Unemployment Insurance Agency. Most claimants receive benefits for up to 26 weeks.',
 'Up to $362/week (~$18,800/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-866-500-0017', 'https://www.michigan.gov/uia',
 13000, 'state', 'MI', null, 'michigan-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Michigan Veterans Affairs Agency (MVAA)', 'Veteran Services',
 'The state agency that helps Michigan veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through veteran service officers and the Michigan Veterans Trust Fund.',
 'Free benefits counseling plus access to state veterans homes and emergency funds',
 'Michigan veterans, active-duty service members, and their dependents',
 '1-800-642-4838', 'https://www.michigan.gov/mvaa',
 5000, 'state', 'MI', null, 'michigan-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Michigan Aging and Adult Services Agency', 'Senior Services',
 'AASA administers Michigan''s 16 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Michiganders 60 and older and their family caregivers',
 '517-373-8230', 'https://www.michigan.gov/osa',
 2000, 'state', 'MI', null, 'michigan-aging-and-adult', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Michigan 211', 'Information & Referral',
 'Michigan 211 is the statewide health and human services helpline. Call 2-1-1 or visit mi211.org to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Michigan needing help finding local services',
 '211', 'https://mi211.org',
 0, 'state', 'MI', null, 'michigan-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),

-- ── MISSISSIPPI (9) ───────────────────────────────────────────────────
('Mississippi Medicaid', 'Health Insurance',
 'Mississippi Medicaid provides health coverage including doctor visits, hospital care, prescriptions, and preventive services. Mississippi did not expand Medicaid for non-disabled adults, so most adult coverage is limited to parents of minor children, pregnant women, and people with disabilities.',
 'Full health coverage at little to no cost',
 'Low-income parents of minor children, pregnant women, people with disabilities, seniors, and children',
 '1-800-421-2408', 'https://medicaid.ms.gov',
 15000, 'state', 'MS', null, 'mississippi-medicaid', true,
 'Mississippi did not expand Medicaid. Most adults without children, disability, or pregnancy do not qualify regardless of income.',
 '{"max_income_percent_fpl": 138, "min_age": null, "max_age": null, "required_situations": ["single_parent", "pregnant", "disability"]}'::jsonb),
('Mississippi SNAP', 'Food Assistance',
 'Mississippi''s Supplemental Nutrition Assistance Program provides monthly food benefits on an EBT card. Administered by the Department of Human Services.',
 'Up to ~$975/month for a family of four',
 'Mississippi households with gross monthly income at or below 130% of the federal poverty level',
 '1-800-948-3050', 'https://access.ms.gov',
 11676, 'state', 'MS', null, 'mississippi-snap', true, null,
 '{"max_income_percent_fpl": 130, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Mississippi TANF', 'Cash Assistance',
 'Monthly cash assistance for very low-income Mississippi families with minor children, plus job placement services. Mississippi TANF benefits are the lowest in the nation.',
 'Up to ~$260/month for a family of three',
 'Mississippi families with minor children and very low income',
 '1-800-948-3050', 'https://access.ms.gov',
 3500, 'state', 'MS', null, 'mississippi-tanf', true, null,
 '{"max_monthly_income": 600, "min_age": null, "max_age": null, "required_situations": ["single_parent", "low_income"]}'::jsonb),
('Mississippi Home Corporation (MHC)', 'Housing Assistance',
 'Mississippi Home Corporation administers the state''s Smart Solution and Smart6 first-time homebuyer programs, with low-interest mortgages and down-payment assistance. Income and home-price limits vary by county.',
 'Down-payment assistance plus below-market mortgage rates',
 'Mississippi homebuyers meeting MHC program income and home-price limits',
 '1-601-718-4642', 'https://mshomecorp.com',
 10000, 'state', 'MS', null, 'mississippi-home-corporation', true, null,
 '{"max_monthly_income": 8000, "min_age": 18, "max_age": null, "required_situations": []}'::jsonb),
('Mississippi LIHEAP', 'Utility Assistance',
 'Mississippi''s federally-funded Low-Income Home Energy Assistance Program helps qualifying households pay heating, cooling, and crisis energy bills. Administered by the Department of Human Services through local Community Action Agencies.',
 '$300–$1,500 per year toward energy bills',
 'Mississippi households with income at or below 150% of the federal poverty level',
 '1-800-948-3050', 'https://www.mdhs.ms.gov/economic-assistance/liheap/',
 1300, 'state', 'MS', null, 'mississippi-liheap', true,
 'LIHEAP funds are distributed through local Community Action Agencies — call 211 to find your local provider.',
 '{"max_income_percent_fpl": 150, "min_age": null, "max_age": null, "required_situations": []}'::jsonb),
('Mississippi Unemployment Insurance', 'Income Assistance',
 'Weekly cash benefits for Mississippians who lost their job through no fault of their own. Administered by the Mississippi Department of Employment Security. Most claimants receive benefits for up to 26 weeks.',
 'Up to $235/week (~$12,200/year max)',
 'Workers laid off through no fault of their own with sufficient base-period earnings',
 '1-888-844-3577', 'https://mdes.ms.gov',
 13000, 'state', 'MS', null, 'mississippi-unemployment', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["unemployed"]}'::jsonb),
('Mississippi Veterans Affairs', 'Veteran Services',
 'The state agency that helps Mississippi veterans access VA benefits, education aid, employment, healthcare, and emergency assistance through county Veteran Service Officers and four state veterans homes.',
 'Free benefits counseling plus access to state veterans homes',
 'Mississippi veterans, active-duty service members, and their dependents',
 '601-576-4850', 'https://msva.ms.gov',
 5000, 'state', 'MS', null, 'mississippi-veterans-affairs', true, null,
 '{"max_monthly_income": null, "min_age": 18, "max_age": null, "required_situations": ["veteran"]}'::jsonb),
('Mississippi Aging and Adult Services', 'Senior Services',
 'MDHS Division of Aging and Adult Services administers Mississippi''s 10 Area Agencies on Aging, connecting seniors and family caregivers to local services — meals, transportation, in-home care, caregiver support, and benefits counseling.',
 '~$2,000/year in services (meals, transport, care coordination)',
 'Mississippians 60 and older and their family caregivers',
 '1-844-822-4622', 'https://www.mdhs.ms.gov/adults-seniors/',
 2000, 'state', 'MS', null, 'mississippi-aging-adult-services', true, null,
 '{"max_monthly_income": null, "min_age": 60, "max_age": null, "required_situations": ["senior", "caregiver"]}'::jsonb),
('Mississippi 211', 'Information & Referral',
 'Mississippi 211 is the statewide health and human services helpline. Call 2-1-1 or visit myunitedway.com/211 to find local programs for rental and utility assistance, food, healthcare, mental health, childcare, and crisis support. Free, confidential, available 24/7.',
 'Free referral to local assistance programs',
 'Anyone in Mississippi needing help finding local services',
 '211', 'https://www.myunitedway.com/211',
 0, 'state', 'MS', null, 'mississippi-211', true, null,
 '{"max_monthly_income": null, "min_age": null, "max_age": null, "required_situations": []}'::jsonb);
